### ISSUE TITLE
Achievement page Crash

### ISSUE THREAD

**Issue by Drakray** [RootsTeam/Roots#104]
Vanilla GUI: http://pastebin.com/AHUGCtz5
BetterAchievement GUI: http://pastebin.com/pgSEKBr7

Forge 2066
Roots 0.111.0

**Comment by elucent** [comment]
Fixed, I think. I forgot to remove the stopped time achievement from being registered, even though it's no longer initialized. That resulted in an achievement that was registered with no information. I'll push to GitHub and build something later today.
