### ISSUE TITLE
standing stones not working

### ISSUE THREAD

**Issue by DnTheMn** [RootsTeam/Roots#105]
were on forge 2065 all the mods version 1.13c a few people have said there not workng i have also seen there not working

**Comment by Joshi120** [comment]
Also breaking Growth stones crashes the server i can't upload a crashlog due to it isnt my server

**Comment by elucent** [comment]
Standing stones now require redstone power to be active, that could likely be the issue. It seems that the research text explaining that was overwritten in a Git pull. I'll fix it right now.

**Comment by elucent** [comment]
As for @Joshi120's issue, please ask your server admin for a log, it's necessary for me to fix the issue.

**Comment by DnTheMn** [comment]
i had reported the crash when breaking the stones it was a server crash ill dig for the issue now

**Comment by elucent** [comment]
I've fixed this.

**Comment by Joshi120** [comment]
Awesome thanks!

**Comment by elucent** [comment]
I might wait to release it until Roots v0.200, where we'll have a lot more content. Depends on how much longer that takes.

**Comment by DnTheMn** [comment]
your the boss @elucent
