### ISSUE TITLE
[elucent.roots.block.BlockSpiritDoubleSlab:getDrops:175]: DEBUG

### ISSUE THREAD

**Issue by MakerTim** [RootsTeam/Roots#106]
Debug message when i start my instance of minecraft
i got the block breaking extension of JEI, thats breaking every block 5000x to see what it drops

now when it checks the roots mod, its so slow and see a lot of DEBUG messages in my console
could you plz revisit this ? in prev. version it was not a problem

[12:49:55] [Client thread/INFO] [STDOUT]: [elucent.roots.block.BlockSpiritDoubleSlab:getDrops:175]: DEBUG

**Comment by elucent** [comment]
That would appear to be a debug message that I didn't remove. I'll fix it right now.
