### ISSUE TITLE
grown ritual gauge wasted

### ISSUE THREAD

**Issue by jochuan** [RootsTeam/Roots#107]
when you make the growth ritual if you open doors with your hand the gauge bar is wasted
i am using the latest version for 1.9.4

**Comment by elucent** [comment]
The growth ritual has been removed in recent versions, so I'm not going to fix this bug. Why are you using a version to 1.9.4, by the way? Just wondering what packs haven't updated to 1.10.2 yet.

**Comment by jochuan** [comment]
i am not using a modpack i am just sticking with 1.9.4 a litle more to see if thaumcraft and some other mods will update ,anyway 1.9.4 still is a very active version

**Comment by elucent** [comment]
1.9.4 and 1.10.2 are basically the same version. When Thaumcraft updates, it'll likely be directly to 1.10.2, if not an even later version.

**Comment by jochuan** [comment]
it is not only thaumcraft but mo creatures too looks like the author will
make a version for 1.7.10 and then will update to 1.9

2016-08-22 13:02 GMT-03:00 elucent <notifications@github.com>:

**Comment by elucent** [comment]
Mo' Creatures can't be legally used in modpacks, and even then I'd be very surprised if it didn't update immediately to 1.10.2. It's extraordinarily easy, and it's likely it would work without even changing the mod from the 1.9.4 version.
