### ISSUE TITLE
growing stone doesn't seen to work with the latest version roots-1.10.2-0.112.0.jar

### ISSUE THREAD

**Issue by LordHellscream** [RootsTeam/Roots#108]
I just updated to roots-1.10.2-0.112.0.jar and growing stone dont seem to work anymore. its no longer glowing and the plants right next to it no longer seems to grow in accelerated rate as before the update.

**Comment by elucent** [comment]
Standing stones require redstone power to function now. Please add a power source and see if your problem persists.
