### ISSUE TITLE
Client classes accessed from server side.

### ISSUE THREAD

**Issue by ryantheleach** [RootsTeam/Roots#109]
I believe you may be accessing client side classes from the server side, according to the bug report I saw on the Sponge forums.

https://forums.spongepowered.org/t/help-menu-error/14339/1

stacktrace provide by the user: http://pastebin.com/SzrHYpQP

**Comment by elucent** [comment]
Ah, you're correct. I don't think I was even using it anymore in the latest versions, but the import was still there. Fixed!
