### ISSUE TITLE
Runic Tablet clears NBT when opened?

### ISSUE THREAD

**Issue by RJS1997** [RootsTeam/Roots#113]
Using latest versions of Forge, Roots, Akashic Tome and AutoRegLib.
 
I was told by Vazkii to report my problem with his Akashic Tome mod and Roots to here. Whenever I add the Runic Tablet to the Akashic Tome ( Which if you don't know it allows you to store and use modded guides in one item ) and I select the Runic Tablet and open it, It will clear the NBT and change back into a regular Runic Tablet resulting in the Akashic Tome being lost.

This is before I open the Tablet.

![akashic tome 1](https://cloud.githubusercontent.com/assets/20137032/18221410/23d2972a-713a-11e6-9635-3c3ddaef78d1.png)

This is after I open and close the Tablet.

![akashic tome 2](https://cloud.githubusercontent.com/assets/20137032/18221418/3c02f876-713a-11e6-86c0-a7db6293fe49.png)

**Comment by elucent** [comment]
That's very strange. Gimme a sec and I'll fix it.

**Comment by elucent** [comment]
Well, I've removed the resetting of the NBT tag (not sure why that was there honestly, I was getting pretty annoyed with writing documentation when I was writing that code :P), but I am directly setting an NBT tag on the item. I'll be getting a new update out shortly, we'll see if that's a problem then.

**Comment by RJS1997** [comment]
Alright thank you I will get back to you when the next update comes out.

**Comment by RJS1997** [comment]
Latest update fixed it thank you!

**Comment by RJS1997** [comment]
Well the new update fixed the bug for the first page of the book, now when I switch pages it removes the NBT.

**Comment by elucent** [comment]
Ah, didn't see that code. It just needs the same fix I used the first time. I'm going to hold out a bit until I release a fixed version so I don't spam CF with fixes after a major release where there's a lot of bugs expected. I'll get something out tomorrow, early tomorrow at that.

**Comment by RJS1997** [comment]
Latest patch fixed it thanks for all the help!
