### ISSUE TITLE
Lance issues

### ISSUE THREAD

**Issue by gchpaco** [RootsTeam/Roots#114]
So I've been playing around with the new lance in the new Roots.  There's a couple things sort of off I noticed about it:

- if you have a shield in your off hand, you can't use it; you raise it a bit but it doesn't have any effect;
- for a melee weapon which is basically an iron sword plus, it's not enchantable, which limits its usefulness considerably.  In particular, sharpness and looting would be really nice.

**Comment by elucent** [comment]
For the first one, I'll fix that in v0.201, expect that tomorrow.

For the second one, it's intentionally not enchantable. Using spells, you can outstrip the DPS of the sharpness enchantment fairly easily, and with high potency on some offensive spells you can oneshot enemies (for considerably high terra cost). I think having spells and using them is already a considerable buff, and do consider that the lance is unbreakable in addition to its magical powers. Adding on maxed enchantments on top of that would be simply too powerful.
