### ISSUE TITLE
Your Banish Rain Crashes Client

### ISSUE THREAD

**Issue by squirrelkiller** [RootsTeam/Roots#115]
http://pastebin.com/GXu9NCyE

Client only crash when using banish rain.

**Comment by ShadowGamerXY** [comment]
Are you playing on a server?

**Comment by ShadowGamerXY** [comment]
And this problem is not related to banish rain but the new spirits ritual summoning.

**Comment by ShadowGamerXY** [comment]
Ok i have found the issue as it says in the runic tablet you need 4 different flowers as incense and it appears if you do not have those flowers it crashes the game.

**Comment by ShadowGamerXY** [comment]
OK I tested every ritual and went through the code and it all works as it should, so if you still get this problem or if you get it after 0.201 update please reopen the issue and give us more info that  we can work with,

**Comment by squirrelkiller** [comment]
I am going to argue that is has NOTHING to do with spirits https://youtu.be/65XoHrme9IY

**Comment by ShadowGamerXY** [comment]
I am sorry but as i asked are you playing on a server because that makes things a bit different. If you are not the crash reports points at the spirit summoning ritual that I fixed and it works fine. I will test it more but I spent like an hour testing all the rain and spirit rituals and I got 0 crashes.

**Comment by ShadowGamerXY** [comment]
And the code seems fine nothing that could conflict with server/client and least I cant see it.

**Comment by squirrelkiller** [comment]
Yes I am on a server. If you would like to see the pack if you think maybe it is a weird interaction: https://minecraft.curseforge.com/projects/strifecraft/files/2328210

Bug Elucent sometime about getting onto said server if you want to see the setup, it isn't going to be modified until likely v0.201 is out as I won't be looking at roots for a short while it appears.

**Comment by ShadowGamerXY** [comment]
I will do server side testing to see what is the real problem but i think I fixed it

**Comment by elucent** [comment]
This is fixed in my IDE, releasing a new version now, will push changes soon.
