### ISSUE TITLE
Console Spam [STDOUT/blockdrops]: [elucent.roots.block.BlockDoubleSlabBase:getDrops:111]

### ISSUE THREAD

**Issue by MrNinja93** [RootsTeam/Roots#117]
May or may not be an issue but theres a substansial amount of entries being logged in console repeating 

> [Client thread/INFO] [STDOUT/blockdrops]: [elucent.roots.block.BlockDoubleSlabBase:getDrops:111]: DEBUG

 and

> [Client thread/INFO] [STDOUT/blockdrops]: [elucent.roots.block.BlockSpiritDoubleSlab:getDrops:175]: DEBUG

In total 120000 lines of just those two repeating constantly over a 1 min period.

**Versions**
Roots -1.10.2-0.201.0
Forge 2076
MC 1.10.2

**Comment by MrNinja93** [comment]
Penny just dropped on cause... Blockdrops JEI addon installed Version 1.10.2-1.0.10

Also reported there by someone else https://github.com/MrRiegel/BlockDrops/issues/19

Blacklisting roots in blockdrops fixes it

**Comment by elucent** [comment]
Ah, figures I'd forget some debug text. I'll fix it and release a new version soon.
