### ISSUE TITLE
Console Spam Galore

### ISSUE THREAD

**Issue by drewbit** [RootsTeam/Roots#118]
Some of my players have started roots, as far as I'm aware they've just now gotten sprites. Something is spamming my console constantly, it's quite annoying. Is this intended?

If it is, mind telling me what's causing it so I can go get rid of it?

Log: http://pastebin.com/qEx305Ar

Roots version: roots-1.10.2-0.201.0

**Comment by elucent** [comment]
Definitely not intended, gimme a few minutes to fix it. I was been planning on releasing a little bugfix update tonight anyway, I'll just throw this in.

**Comment by elucent** [comment]
I'm not sure exactly what's causing this. I *may* have just fixed it, but considering that I couldn't replicate the bug in the first place, I can't be sure. I'll release a new version, let me know if this is fixed.

**Comment by drewbit** [comment]
Just finished updating, it's still happening.

Here's the log again if needed: 
http://pastebin.com/AJc6H90T

**Comment by elucent** [comment]
That's very strange. I'll take another crack at it when I next get a chance.

**Comment by Morpheus1101** [comment]
We're using roots on the MMD-Dev server and arent seeing any console spam
