### ISSUE TITLE
Ancient Hourglass time stop activities

### ISSUE THREAD

**Issue by VallenFrostweaver** [RootsTeam/Roots#120]
Very nice item. I like the balance. Not sure if this is as intended. If so, please close this. When it activates I can't eat or drink until the time stop effect ends but splash potions still work during the time stop.

**Comment by elucent** [comment]
Huh, that's a little weird. Is the time stop affecting your motion at all?

**Comment by VallenFrostweaver** [comment]
Nope.

**Comment by elucent** [comment]
That is definitely not intended, but I have no clue how it's happening. I'll take a look soon, currently taking a little break from serious Roots development to mess around with some stuff I rarely mess around with, like fluid handling and inventories.
