### ISSUE TITLE
Roots Staff reverts to plain staff after a few uses

### ISSUE THREAD

**Issue by choekstr** [RootsTeam/Roots#121]
I am running FTB Unstable 1.10.2 server and client which comes with roots-1.10.2-0.110.0, which had issues, so I upgraded to roots-1.10.2-0.202.0 while keeping the same 2073 forge version.  

When I create the electric spark staff with any combination of modifiers in any quantities (3 glowstone, 1 glowstone, 1 redstone, 1 gunpowder, 2 and 1, etc etc) it creates the staff.  Anywhere from 1 use to 4 uses it immediately changes to a plain staff with no effects.  I have created 5 staffs using:
1 glowstone block
1 glass
1 poison potato
1 sugar cane
1 dragon eye
3 of any combination of glowstone/redstone/gunpowder
1 stick

I get the staff with the appropriate modifiers and ~50 uses depending on which modifiers I pick but when I use the staff it discharges lightning properly on first try but anywhere from the 2nd to the 6th time it magically transforms to a plain staff with white tip and no abilities or effects or modifiers and it is no longer usable.  I then have to recreate the staff and rinse and repeat.

There doesn't seem to be any rhyme or reason as to why it is doing this, like only partially casting, or using it on a particular mob.  I am charging creepers with it but it has happened on pigs and zombies and skeletons as well.  There also is no client console message or server console message that shows up either.

**Comment by choekstr** [comment]
Here is the issue on camera: https://youtu.be/txNqu8cBjeQ?t=522

**Comment by elucent** [comment]
That's a very weird issue. Sorry I haven't responded sooner, I've been messing around with some other mod concepts. I'll take a look at this soon, but I have no idea what's causing it.

**Comment by choekstr** [comment]
Thanks, appreciate you taking a look.  I couldn't get a pattern down as to why.  I have a botania haste pendant which I thought might be affecting it but doesn't seem to.  I have watched others use it just fine.  Something not normal in either the pack or in my inventory affecting it but just can't for the life of me figure out what.

**Comment by werty1124** [comment]
I've tried to recreate this multiple times to fix it but I cant seem to be able too

**Comment by choekstr** [comment]
That's what I figured would happen.  I haven't seen any other people playing in their worlds that have this happen to them and I have tried to figure out what is the cause.  Clearly an isolated incident and not widespread.  If you want you can close this as it probably isn't affecting anyone else.  We can just chalk it up to weirdness and assume it won't happen to anyone else.

**Comment by werty1124** [comment]
Alright going to close this. If you can think of anything else that may be causing it just comment in this issue again and ill see if I can figure it out.
