### ISSUE TITLE
Growth Standing Stones give no effect

### ISSUE THREAD

**Issue by Eyrion** [RootsTeam/Roots#122]
Playing All the Mods modpack version 1.19 

"Growth" Standing Stones give no green particle effects nor apply any growth effect to nearby crops.

Solved: Stones now require a redstone signal - needs updated info to in-game documentation

**Comment by elucent** [comment]
The latest versions have updated documentation, it's quite possible All The Mods is out of date. You could check the version in the pack -- anything below v0.200 won't have the updated documentation.
