### ISSUE TITLE
Crash while using tablet

### ISSUE THREAD

**Issue by SpitefulFox** [RootsTeam/Roots#125]
[crash-2016-09-22_01.19.07-client.txt](https://github.com/RootsTeam/Roots/files/488976/crash-2016-09-22_01.19.07-client.txt)

Got a crash while looking through the pages of the entry on living tools.

**Comment by elucent** [comment]
I believe I may have fixed this, but since I haven't encountered this bug myself I can't confirm if it works or not. I'll release a new version very soon.
