### ISSUE TITLE
Casting Frost Shard via Staff throws NoSuchMethodError

### ISSUE THREAD

**Issue by MushroomDynamo** [RootsTeam/Roots#128]
[crash-2016-09-30_04.46.11-server.txt](https://github.com/RootsTeam/Roots/files/503157/crash-2016-09-30_04.46.11-server.txt)

Running a small private server with Forge #2093, Roots 1.10.2-0.203.0. One of my players tried to cast a Blistering Cold spell through his crystal staff and immediately triggered server FUBAR. 

I tested this on a local server with just Roots and, while the server didn't crash (oddly enough) the log immediately spat out the same error every time I used an identical staff.

Any ideas?

**Comment by werty1124** [comment]
working on it
