### ISSUE TITLE
Weather ritual not working

### ISSUE THREAD

**Issue by ranma862** [RootsTeam/Roots#131]
The summon/banish rain rituals are not being recognized. In creative testing, I have an altar set up with the 8 standing stones and braziers within 9x9, and I know the altar and stones are functional in general because the time shift ritual and living tools ritual worked just fine.

When I put 1 vine and 1 old root into braziers, light them, and put either 1 wheat or 1 lily pad on the altar and shift-right-click the altar, it says "No valid ritual found!" This happens whether it is raining or clear weather with either ritual.

I am using Roots-1.10.2-0.204.0.

**Comment by elucent** [comment]
You need to be above y=128 IIRC.

**Comment by ranma862** [comment]
Huh, okay. That did it. Please update the Runic Tablet with some sort of hint about that, thank you!

**Comment by elucent** [comment]
Sure, I thought it mentioned it but apparently it does not.
