### ISSUE TITLE
1.10.2-0.204.0 crashes dedicated Forge 1.10.2 build 2107 on startup

### ISSUE THREAD

**Issue by kreezxil** [RootsTeam/Roots#132]
crash report:
https://gist.github.com/87af07ac0cbe6b3a527911c0f4e911c4

fml server latest:
https://gist.github.com/79b52c518a6c375b9504d7b7673b40cb

**Comment by ShadowGamerXY** [comment]
When does this happen because i tested it and I got no errors.

**Comment by ShadowGamerXY** [comment]
If you have this issue in the future and if you can provide me more info please reopen this issue.
