### ISSUE TITLE
Crash after zooming out of roots achivements screen

### ISSUE THREAD

**Issue by JAWSAWN** [RootsTeam/Roots#135]
https://gist.github.com/JAWSAWN/73a046747fe599b58e9b31c2ee5b1e72

Not sure if it happens to every mod but i scrolled up on roots achivements and zoomed out. And it froze and crash.

**Comment by ArbitraryHubris** [comment]
crash when dragging the roots achievement chart up to the very top in Infinity Lite pack.  roots-1.10.2-0.204.0.jar

http://pastebin.com/GareUuW7

**Comment by elucent** [comment]
I honestly have no idea why this is happening. I'll get some other input.

**Comment by elucent** [comment]
Apparently all I needed to do was rearrange the achievement layout. Fixed!

**Comment by ArbitraryHubris** [comment]
@elucent Thanks!
