### ISSUE TITLE
Staffs sometimes lose their data and become blank/useless

### ISSUE THREAD

**Issue by Febilian** [RootsTeam/Roots#136]
I'm still trying to pinpoint what causes this specifically as I play, but apparently I keep managing to do SOMETHING in my survival worlds to my offhand staves that makes them lose all of their data(durability, the spell contained, basically anything including the coloration. It just turns blank white and has no special name or tooltip).

I do know that it has happened with multiple different kinds of basic staves across different maps so far, the most recent being an unmodified Insanity spell that was around half durability before it became blank. So it was around for quite a while before it happened.

The only potential common factor I can recall right away was sleeping in a Quark-added bed sometime before it happened every time(I never seem to notice it right away, so I'm not sure exactly when the staves became blank), but on the other hand, I've slept in the same bed(s) other times without it happening at all. It might not be related to that at all, honestly, but I thought I'd throw it out there just in case.

The server console and client console logs are both incredibly unhelpful in this regard.

I'm using 1.10.2 recommended Forge and the latest version of Roots(.204).

I'll comment with more information if I am able to find a clue as per potential causes. Any suggestions would be welcome; for now, here is a mod list:

> AkashicTome-1.0-4.jar
> AppleCore-mc1.10.2-2.0.1.jar
> AppleSkin-mc1.10.2-1.0.4.jar
> AutoRegLib-1.0-2.jar
> BabyAnimals-1.9.4.jar
> Baubles-1.10.2-1.3.0.jar
> BiomesOPlenty-1.10.2-5.0.0.2089-universal-2.jar
> BiomeTweaker-1.10.2-2.1.229.jar
> BloodMagic-1.9.4-2.1.0-66.jar
> Botania r1.9-337.jar
> Ceramics-1.10.2-1.1.2.jar
> Chisel-MC1.10.2-0.0.7.3.jar
> chiselsandbits-12.6.jar
> Clipboard-1.10.2-1.0.0.jar
> CookingForBlockheads_1.10.2-4.2.16.jar
> CosmeticArmorReworked-1.10.2-v2a.jar
> CraftTweaker-1.10.2-3.0.13.jar
> creeperconfetti-1.2.1.jar
> cyberware-1.9.4-1.10.2-beta-0.2.3.jar
> DynamicSurroundingsUnofficial-1.10.2-3.0.6.1BETA.jar
> embers-0.015.jar
> EnderCompass-1.9.x-1.2.3.2.jar
> exhaustion-tweaks-1.10.2-1.1.jar
> extraalchemy-0.3.0.3-release.jar
> ExtraGolems[1.10.2]-6.02.jar
> ezstorage-2.2.5.jar
> FastLeaveDecay-MC1.10.2-1.2.2.jar
> flatcoloredblocks-mc1.10-v4.3.jar
> flowergirls-1.10.2-1.1.0.jar
> Forgelin-1.0.5.jar
> GiacomosFishingNet1.10.2-1.4.4.jar
> Guide-API-1.10.2-2.0.2-45-2.jar
> hardcoreWither-1.10.2-2.0.0-alpha3-961d92c-universal.jar
> IronBackpacks-1.10.2-2.2.10.jar
> itemscroller-1.10.2-0.7.1.jar
> jei_1.10.2-3.13.0.339.jar
> journeymap-1.10.2-5.2.4-unlimited.jar
> literalascension-1.10.2-0.0.2.0.jar
> llibrary-1.7.1-1.10.2.jar
> Login_Shield-1.10.2-14-g4618728.jar
> modnametooltip_1.10.2-1.6.0.jar
> moreoverlays-1.8-mc1.10.2.jar
> Morpheus-1.10.2-3.1.9.jar
> NaturalPledge-r1.6.jar
> NaturesCompass-1.10.2-1.2.0.jar
> Neat 1.3-12.jar
> NoMobSpawningOnTrees-1.1.7-mc[1.9.4-1.10.2].jar
> PackingTape-1.10.2-0.6.0.jar
> Pam's HarvestCraft 1.9.4-1.10.2g.jar
> PotionPacks_1.10_b6b.jar
> Psi-r1.0-41-2.jar
> Quark-r1.0-57.jar
> Reliquary-1.10.2-1.3.3.585.jar
> ResourceLoader-MC1.9.4-1.5.1.jar
> roots-1.10.2-0.204.0.jar
> roughMobs1.0.8.1-1.10.2.jar
> RTG-1.10.2-4.1.1.5.jar
> ShadowMC-1.10.2-3.4.9.jar
> SimpleInventoryStarter-0.1.jar
> SoulShards-TOW-1.10.2-2.6.4-44.jar
> SpartanShields-1.10.2-1.0.jar
> SpiceOfLife-mc1.9.4-1.3.6.jar
> theoneprobe-1.10-1.1.6.jar
> topaddons-1.10.2-0.8.0.jar
> usefulnullifiers-1.2.1.jar
> weaponcaseloot-1.10.2-4.0.1.jar
> WIRED-1.3.3.jar
> WTF-Expedition_1.10.2_v1.1.jar

**Comment by elucent** [comment]
Are you on a server?

**Comment by Febilian** [comment]
Yes, I am indeed on a server. Again, if I can find any other clues, I'll try to help.

**Comment by Febilian** [comment]
I recently died on my server(not for the first time, however) and I noticed my staff became blank. Could it be related to the gamerule I have active - keepInventory=true? My only other guess with what I did recently was go through a nether portal.

**Comment by elucent** [comment]
I don't believe it is, my best guess is that it's some kind of synchronization issue.

**Comment by elucent** [comment]
Um, I might have found a really stupid mistake. Try shift+right clicking a few times, does it fix the problem?

**Comment by Febilian** [comment]
I will try that the next time it happens and let you know how it goes.

**Comment by Febilian** [comment]
Oddly enough, shift-right clicking on a normal staff causes it to cycle through some 'blank' states like a crystal staff. Guess that's what was happening! Haha.

**Comment by elucent** [comment]
Yeah, I'll get it fixed right away. Might be a little bit until a new release though, I have some stuff I want to add that can't really be added in parts.

**Comment by elucent** [comment]
Fixed this a while ago, forgot to close the issue. Expect it in the next release!
