### ISSUE TITLE
Crash: Creeper Exposion near the standing stone

### ISSUE THREAD

**Issue by BeekeeperGilgrim** [RootsTeam/Roots#137]
Had a creeper explode on my while near my Ritual setup. Both Mundane and Attuned standing stones are within the explosion range. Game crashes, Reloading game after crash reloads the creeper to explode and crash me again. This is the second time I've had this same result.
[crash-2016-11-03_22.36.42-server.txt](https://github.com/RootsTeam/Roots/files/570617/crash-2016-11-03_22.36.42-server.txt)

I was on the 202 version, but updating to your current 204 version still has the same result. I've either to figure out how to edit the game files to switch to peaceful or remove roots to remedy this.

**Comment by elucent** [comment]
I've fixed this in my other mod, Embers. I'll get a fix out for the next release, though it might be a little while since I have a lot of content to add in addition to a ton of bugfixes.

**Comment by BeekeeperGilgrim** [comment]
Thanks. I've managed to pause the game as I loaded right before the explosion crash to set to peaceful. I can begin playing again. I'm moving my ritual setup to an indoor location to avoid this issue

**Comment by elucent** [comment]
I have added the code for this fix to the mod.
