### ISSUE TITLE
Suggestion(if possible): make Regeneration spell detect non-vanilla flowers

### ISSUE THREAD

**Issue by Febilian** [RootsTeam/Roots#138]
I don't know if this would be possible to do in any reasonable way. Even rudimentary support, such as for Biomes O Plenty flowers, would probably be appreciated by a lot of people - it's a little annoying to see flowers all around you but not get healed by the spell because they aren't from vanilla Minecraft.

Just a thought. Take it as you will!

**Comment by elucent** [comment]
Shouldn't be too hard, I'll comment again in this thread if I get it implemented or encounter any issues.
