### ISSUE TITLE
Growth spell no longer seems to affect nether wart

### ISSUE THREAD

**Issue by Febilian** [RootsTeam/Roots#140]
Either that, I'm incredibly unlucky, or an early-game staff made with an old root and this component is near useless for growing crops/etc no matter what you do. I would understand if the latter is the case, considering that it isn't a terribly difficult spell to make compared to some others, but it's a bit annoying to use up nearly the _entire staff_ without a single growth tick on the nether wart(it was only not the entire staff because I was testing whether it was effective on my sizable plantation of other crops when I was standing in the middle of it, maybe out of the entire staff, only one or two plants had their growth accelerated!).

I just remember making an issue ages ago about nether wart growth and assumed it was still implemented after I was told it was added. Please correct me if I'm wrong and it was removed at some point!

**Comment by elucent** [comment]
Hmmm, that's strange. Most likely it just got removed at some point.

**Comment by elucent** [comment]
Turns out this spell was just totally bugged and doesn't work in the current version. It's fixed now.

**Comment by JaSpr** [comment]
Do the growth stones work with nether wart??

**Comment by elucent** [comment]
Maybe? I don't know, it's been so long since I touched the 1.10 version.

**Comment by JaSpr** [comment]
It doesn't appear to, but i'm not gonna request that it should.  I think it's fine as it is.
