### ISSUE TITLE
JEI compatibility issue

### ISSUE THREAD

**Issue by mankra** [RootsTeam/Roots#141]
Forge version: 1.10.2-12.18.2.2120
Roots version: 0.204.0
JEI version: 3.13.2.360

The following items are listed twice in the JEI item list with the second ones having no texture:
- Debug Wand
- Runestone Slab
- Runestone Brick Slab
- Runestone Tile Slab
- Wildwood Slab
- Otherworld Slab
- Otherworld Brick Slab

I put the Debug Wand on the JEI blacklist, but maybe you could give it a standard texture for people who don't use the blacklist feature.

**Comment by mankra** [comment]
The-Fireplace [fixed the issue](https://github.com/The-Fireplace/Adobe-Blocks/issues/7). Maybe he can help.

**Comment by elucent** [comment]
I see. It would require making JEI a dependency in building Roots, which isn't too bad, but it is a little bit of a hassle on my part that I currently don't have to deal with. For a purely aesthetic bug like this, it'll probably wait until I make up my mind about how to add JEI support.

**Comment by mankra** [comment]
I didn't notice he made JEI a dependency. That's really not the best solution.

**Comment by elucent** [comment]
It's only a build dependency, to be clear. Still a little hassle on my part, but it's not much, and it shouldn't affect the end user. This is just rather low on my priority list -- a few missing textures is no big concern.

**Comment by mankra** [comment]
I worked around the issue by putting the unwanted items on the JEI blacklist.
