### ISSUE TITLE
Crash with IC2 [v. 0.205] 

### ISSUE THREAD

**Issue by al132** [RootsTeam/Roots#145]
I have been getting the following crash with IC2 after upgrading to the newest version of roots.

https://gist.github.com/al132/8f7fa616b1402ec9270b2e0a5bf69f62

Downgrading roots fixes the issue.

**Comment by elucent** [comment]
Try this? https://dl.dropboxusercontent.com/s/7rrz1f1fr3daxp2/roots-0.206.jar?dl=0 (warning: direct download)

**Comment by al132** [comment]
Thanks for the quick response; that did seem to fix it.
