### ISSUE TITLE
Regeneration not working in 0.206

### ISSUE THREAD

**Issue by MaciejJaromin** [RootsTeam/Roots#146]
Minecraft version: 1.10.2
Roots version: 0.206
Forge version: 12.18.2.2151
The Regeneration spell seems to have no effect in the new version. Rose's Thorns works fine, I haven't tested anything else yet.

**Comment by elucent** [comment]
What flowers do you have around you?

**Comment by MaciejJaromin** [comment]
I was testing it with 5-6 dandelions.

**Comment by MaciejJaromin** [comment]
And I just got a crash while casting, caused by a bad bound value for the RNG.
[crash-2016-11-22_18.27.27-server.txt](https://github.com/RootsTeam/Roots/files/607083/crash-2016-11-22_18.27.27-server.txt)

**Comment by elucent** [comment]
Closing as 1.10.2 is no longer supported.
