### ISSUE TITLE
Crash when throwing the last ender pearl in a stack

### ISSUE THREAD

**Issue by luckdemon** [RootsTeam/Roots#147]
Threw last ender pearl in stack, crashed as soon as pearl hit the ground. Also crashes if I throw 1 ender pearl out of a stack and then switch slots to an empty hand before it lands.
http://pastebin.com/CH7vRxHQ

**Comment by luckdemon** [comment]
Just to add additional info here, the pixie stone also causes some odd behavior by itself. When using it to fly up, if I switch off of it before landing I take no fall damage, if I exhaust it going straight up and then fall with it in hand, I take minimal fall damage. If I switch off of it mid-flight and land, the ground landing particles appear twice, If I switch back to the pixie stone after the first ground landing particles, but before the second, I will take damage.

**Comment by MysticAura** [comment]
Can confirm the ender pearl bug. Crashed the server instantly.
MC: 1.10.2
Forge: 2151
Mod Version: 0.206

[Crash Log](http://pastebin.com/YbKn6rU8)

@luckdemon you may want to make a second issue for your second comment, as they are separate issues

**Comment by Lunchington** [comment]
http://pastebin.com/YustZxSH 

same error

**Comment by al132** [comment]
We've been having more troubles with this issue. Our server crashes every single time a particular player tries to join with this error, and they said the last thing they did before it happened was throw an ender pearl. I think we also had this happen with another player a while back.

**Comment by elucent** [comment]
Fixed, I was taking some time to work on my other mods but I'll get a new version out later today.
