### ISSUE TITLE
Server thread crashes - LivingHurtEvent

### ISSUE THREAD

**Issue by xenoflot** [RootsTeam/Roots#149]
Hi,

I'm assembling and testing a new pack at the moment and noticed a thread crash showing up occasionally. I wasn't doing anything in particular when it happened, just digging a hole.  It seems to be related to Roots.   It's not crashing the server but I thought I'd mention it anyway.  Pastebin includes what I think is the relevant part and the full mod list.

http://pastebin.com/Mh2DkdxA

Roots 206
Forge 2122

Cheers!

**Comment by CerulanLumina** [comment]
Getting the same issue in 206, think it's because a lack of a null check on the getItem() call in EventManager:572. https://github.com/RootsTeam/Roots/blob/master/src/main/java/elucent/roots/EventManager.java#L572

**Comment by elucent** [comment]
Seems probable. I'll fix it and upload a fix in the near future.

**Comment by elucent** [comment]
Fixed, I'll upload a new version later today.
