### ISSUE TITLE
Server crash when breaking attuned standing stone

### ISSUE THREAD

**Issue by syntaxaire** [RootsTeam/Roots#151]
This crash occurred when breaking an attuned standing stone that was near an altar but wasn't put in the right place.
Crash log: https://gist.github.com/syntaxaire/8676b1e246585246096d3df145c289a5
It crashed the server twice while removing the two attuned stones missing in this screenshot.
https://i.imgur.com/0ddGlCT.png
I was using a Tinker's Construct pickaxe and removed the attuned standing stones by knocking out their bottom block. They did end up in my inventory after the server came back up.
There was an altar present during the first crash, I took it down before trying to remove the second stone but it still crashed.

**Comment by elucent** [comment]
The altar should have nothing to do with this. I wish it did, because then I'd know what's going wrong. I'll think on this a bit more.

**Comment by elucent** [comment]
Closing as 1.10.2 is no longer supported.
