### ISSUE TITLE
Crash when trying to summon creatures

### ISSUE THREAD

**Issue by Meller127** [RootsTeam/Roots#152]
Tested with Slime and a couple of others
http://pastebin.com/LdTaEYSp

**Comment by syntaxaire** [comment]
Came here to report this. Client crash only for me, summoning a lesser spirit.
Crash log: https://gist.github.com/syntaxaire/374179cc1d96fc6fb9c60f0c922f146e

**Comment by elucent** [comment]
I'm extremely confused about how this is happening. I'll mess with it a bit more.

**Comment by syntaxaire** [comment]
Is this the same as #148 ?

**Comment by elucent** [comment]
I believe so, that issue was probably pre-emptively closed.

**Comment by Efimero** [comment]
had the same crash when summoning a lesser spirit
it's a null pointer when ticking the entity
like you're ticking it before it actually spawns??? idk

**Comment by elucent** [comment]
Fixed this, I'll get a new release out later today.
