### ISSUE TITLE
Roots contains code that gives its authors special abilities on servers

### ISSUE THREAD

**Issue by syntaxaire** [RootsTeam/Roots#153]
EventsManager.java contains code giving the authors special abilities on any server running Roots:
They can use a special command to freeze all other players for 20 seconds (unless they have an ancient hourglass), or
They can fly if they are carrying a certain item from Tinker's Construct.
This is really unprofessional to leave in a mod. Code like this should never be running on someone's server, even if it is never likely to be used.

**Comment by elucent** [comment]
It's a joke.

**Comment by tkdberger** [comment]
>They can fly if they are carrying a certain item from Tinker's Construct.

`player.getHeldItemMainhand().getItem().getRegistryName().toString().equals("tconstruct:moms_spaghetti")`

You know, somehow I doubt that item actually exists

**Comment by elucent** [comment]
It does, actually. It's from a spaghettimancy joke I made on a discord channel. It can only be found in dungeon chests rarely, and has an extremely lengthy processing method, so it's *probably* more costly than an angel ring, to be fair.

Regardless, it's pretty clearly a joke.

**Comment by syntaxaire** [comment]
It would be a joke if it was commented out. Do you really think this gives a good impression?

**Comment by elucent** [comment]
Why does it matter to you, or any user pretty much? It's a joke feature that none of the dev team would ever use, other than perhaps "hey guys check out this joke feature I put in Roots" on some server. And, as far as dev-specific features go, at least I put in *some* semblance of balance to them (though that's part of the joke pretty much). I don't see anyone complaining to RWTema about being able to turn Etheric Swords into Kikokus.

**Comment by tkdberger** [comment]
:popcorn:
