### ISSUE TITLE
Server crash whilst using the spell Blistering cold

### ISSUE THREAD

**Issue by Freddo42** [RootsTeam/Roots#154]
Hey thought I should post this.

I am using the FTB mod pack Infinity lite version 1.3.3 for minecraft version 1.10.2

The server crashes when we try to use a spell called blistering cold with the combat staff. I've not tried with other staves. Other spells were working without a server crash.

Attached are the crash report logs I have from the FTB server. Should you require any information, please do not hesitate to ask.
[crash-reports.tar.gz](https://github.com/RootsTeam/Roots/files/641074/crash-reports.tar.gz)

**Comment by Tehkiah** [comment]
Tried this with a projectile staff and it instantly crashed the server on cast.

**Comment by elucent** [comment]
Closing as 1.10.2 is no longer supported.
