### ISSUE TITLE
Suggestion: Clarify what modifiers do for each spell

### ISSUE THREAD

**Issue by DeliciousTea** [RootsTeam/Roots#158]
It'd be nice to know what potency, efficiency, and area do exactly for each spell. For instance, I assumed that adding potency to Infection would increase the damage per tick, but it actually slightly increases the duration. It would also help with testing and adding issues to the tracker to know exactly how a spell should function vs its actual effects :)

**Comment by elucent** [comment]
Closing as 1.10.2 is no longer supported.
