### ISSUE TITLE
Chunk crash when do Ritual for Sprites or Monster (Single & Multiplayer)

### ISSUE THREAD

**Issue by KetMaliss** [RootsTeam/Roots#160]
When i try to do the ritual for Monster or Sprite, the Chunk crashes, i tried this in a Singleplayer Game with the same result. When i relog, the Monster or Sprite is there. We use the Hermitpack (Version 1.51), with Draconic Evolution.

**Comment by kingOlegos** [comment]
I'm having the same problem. I don't think it's caused by Draconic Evolution, because I'm not using it.

**Comment by VallenFrostweaver** [comment]
This issue has since been fixed with an updated version of Roots (0.208). Regrettably, HermitPack hasn't updated this yet.

**Comment by KetMaliss** [comment]
Ok, thx for the answer, Server will be updatet soon.
