### ISSUE TITLE
Projectile Staff and Acceleration Potency 3

### ISSUE THREAD

**Issue by lordchubz** [RootsTeam/Roots#161]
Created a Projectile Staff with several spells, tried using the Acceleration spell on a furnace filled with raw porkchop to see how fast it would speed up, and my client crashed.  My server did not crash though.

[crash-2016-12-23_21.56.04-client.txt](https://github.com/RootsTeam/Roots/files/671638/crash-2016-12-23_21.56.04-client.txt)

**Comment by elucent** [comment]
Closing as 1.10.2 is no longer supported.
