### ISSUE TITLE
Solar Smite on another player causes a crash

### ISSUE THREAD

**Issue by dshadowwolf** [RootsTeam/Roots#162]
While using Roots in my pre-alpha 1.10 mod-pack I caught a friend (and mod-pack tester) in the splash of an electric spark spell. He tried to hit me with a Solar Smite and his client crashed. The log of the crash indicates it happened in the application of the spell effect.

<details>
<summary>Top of the stack trace is in this nice spoilerish block, full log from his crash-reports directory will be added as a link to pastebin.</summary>
<p>java.lang.NullPointerException: Unexpected error
	at elucent.roots.component.components.ComponentSunflower.doEffect(ComponentSunflower.java:44)
	at elucent.roots.item.ItemCastingBase.doEffect(ItemCastingBase.java:190)
	at elucent.roots.item.ItemCastingBase.cast(ItemCastingBase.java:127)
	at elucent.roots.item.ItemCastingBase.func_77615_a(ItemCastingBase.java:93)
</p>
</details>

[crash-report-2016-12-24_17.31.00-client.txt](http://pastebin.com/LDmnsjgg) 

EDIT: The NPE is still an error - because there is nothing on the indicated line that should error, even though PVP on my test server is turned off.

**Comment by elucent** [comment]
Closing as 1.10.2 is no longer supported.
