### ISSUE TITLE
Warding spell produces a white totem (visual bug) [1.10.2 - ver. 0.208]

### ISSUE THREAD

**Issue by Dylan4ever** [RootsTeam/Roots#163]
Hello lads, I was playing around a bit in creative trying out the mod (assembling a modpack for me and a friend o'mine) when I ran across a visual appearance which ought to be a bug of sorts. It is a white totem approximately 2 blocks high with no hitbox.

![2016-12-27_12 13 53](https://cloud.githubusercontent.com/assets/5971389/21498593/38f170d2-cc2e-11e6-8fc9-39e72a90921b.png)

My mod list:
![knipsel](https://cloud.githubusercontent.com/assets/5971389/21498658/e61e61f2-cc2e-11e6-9cb9-d85343fa4356.PNG)

I have already verified that OptiFine is not the cause. Method of verification: remove OptiFine, cast spell.

EDIT: Hardcore Darkness is also not the cause. Same method.

**Comment by elucent** [comment]
This is a bug with the spell's entity. I've done similar fixes for other spell entities in the mod, but this one must have somehow slipped past.

**Comment by elucent** [comment]
Closing as 1.10.2 is no longer supported.
