### ISSUE TITLE
Verdant Sprigs don't drop with right click to harvest mod

### ISSUE THREAD

**Issue by SpartanSamuel** [RootsTeam/Roots#164]
I'm in a modpack and this weekend will go through disabling all of the right click to harvest mods to figure out which ones are adding the functionality, but until I figure out specifically which mods this is conflicting with, is there any idea on how to add that to the loot table of crops harvest in this fashion?

MC: 1.10.2
Forge: 12.18.3.2185
Roots: 0.208

**Comment by elucent** [comment]
This isn't really an issue. I couldn't find a way to add support on my end for it, and at some point I realized there was no real point to it. Having to left-click harvest means you have control over whether you get Roots drops or not, which is useful to some people.
