### ISSUE TITLE
Sprites not going in down state

### ISSUE THREAD

**Issue by AstroxV** [RootsTeam/Roots#167]
Playing with 0.208.
Sprites will not go dark and in down state. When I hit them they take damage, but whatever I try, I always end up killing them instead of them going down. I tried puniching them to death so they would hit half a heart but it's not doing anything.
This makes it impossible to "tame" them.

Also they do not respond to the Spirit Font or the Conduits.

**Comment by elucent** [comment]
They no longer do this in 0.208. Does it say that they should in the tablet? If so, I'll change that.

**Comment by AstroxV** [comment]
Yeah it does:
![2017-01-07_20 37 58](https://cloud.githubusercontent.com/assets/24465031/21744608/71cc7e62-d519-11e6-9bc4-5fb61dd7ca20.png)

I think I got the sprites bound to a spirit font. It's a bit unclear if they are when wandering around.

**Comment by elucent** [comment]
Ah, I see, I forgot to update the text.

For the record, the sprites are a bit of a terrible system. So terrible, in fact, that I'm working on a "Roots 2" as we speak with no sprites to be seen. :P

**Comment by AstroxV** [comment]
Aww, I kinda like it when a mod adds an alternate way of creating items or they become a bit repetitive. But I understand if it is something you as a modmaker get annoyed by and are not completely happy about it you want to change it. Keep up the good work and thanks :)

**Comment by elucent** [comment]
Don't worry, if I'm changing anything, Roots 2 will have _way_ more unique ways of getting items than Roots 1. Stay tuned!
