### ISSUE TITLE
Infinite dragon eyes/ender pearls

### ISSUE THREAD

**Issue by Deshiba** [RootsTeam/Roots#168]
Using the SkyFactory 3.0.4 pack placing and breaking chorus flowers consecutive still yields dragon eyes. This means that you will have infinite dragon eyes/ender pearls at relatively no cost. I have yet to test this with only Roots installed.

Preferably chorus flowers should only drop dragon eyes when it has reached age 5 (fully grown).

**Comment by elucent** [comment]
It's supposed to only drop Dragon's Eyes _instead_ of the Chorus Flower, I'm not totally sure why that's not happening. My development efforts have mostly moved on from Roots for 1.10.2, so while this might get fixed, I'm prioritizing other mods unfortunately.

**Comment by KingDGrizzle** [comment]
I'm pretty sure its happening, yet still, farming the flowers are easy, and this can't be automated, as fake users won't trigger it.

**Comment by elucent** [comment]
Closing as 1.10.2 is no longer supported.
