### ISSUE TITLE
[Roots 2] Powder pouch filling recipe deletes items.

### ISSUE THREAD

**Issue by laserlemons** [RootsTeam/Roots#172]
If you stick a random item into the crafting table while you are filling the powder pouch it will delete the item.

Before:
![2017-01-16_18 50 26](https://cloud.githubusercontent.com/assets/6501298/22004951/ce109b4a-dc1c-11e6-97d9-091a65d6fe82.png)

After:
![2017-01-16_18 50 40](https://cloud.githubusercontent.com/assets/6501298/22004953/d00855dc-dc1c-11e6-9133-762713824196.png)

**Comment by elucent** [comment]
Huh. Easy enough fix. I'll get to it in a little while.

**Comment by elucent** [comment]
Should be fixed now, I'll release a new version soon.

**Comment by elucent** [comment]
Okay, the time for new releases is nigh.
