### ISSUE TITLE
[Roots 2] Harmful spells don't respect PVP being turned off

### ISSUE THREAD

**Issue by Febilian** [RootsTeam/Roots#175]
At the very least, I was able to ignite my friend with the wildfire spell despite PVP being turned off. While entertaining in a way, could also be very annoying for collaborative multiplayer and fights.

You may remember me as the person who was complaining about a similar issue in the first Roots some time ago. Heh. I remember a config option in the first Roots, but there seems to be no such thing in Roots 2 as of yet, so I thought I would bring it up just in case you wanted to do something about it.

**Comment by elucent** [comment]
Yeah, I just haven't implemented this back in yet. I can.

**Comment by elucent** [comment]
Added support, finally!
