### ISSUE TITLE
[Roots 2] Thatch blocks don't block rain visuals

### ISSUE THREAD

**Issue by Febilian** [RootsTeam/Roots#176]
I have no idea how intended this is, given that thatch is admittedly not the most secure of building materials in general, but at the same time it's recommended in one of the books to use it as a roof, which seems a bit counterproductive when the roof made of it doesn't block the rain/weather.

This is obviously a fairly minor bug(if it is a bug) but I thought I'd report it nonetheless, just in case.

**Comment by elucent** [comment]
Nah, that's not intentional. I'll fix it right away.

**Comment by elucent** [comment]
The fix will be included in the next version. Hopefully coming soon!
