### ISSUE TITLE
[Roots 2]Powder pouches act weird with 1 herb in them

### ISSUE THREAD

**Issue by LWnellA** [RootsTeam/Roots#177]
Powder pouches seems to hate having its number fall below 1, because it never does.
If you have 1 herb in your pouch and try to cast a spell that costs 1 herb, the spell won't trigger, as if you have no herb in your pouch.
If you try to cast a spell that costs less than 1 herb, it works like you'd expect it to, but the number doesn't go down and stays on 1. If you add more herbs, the number reads 'number of herbs added + 1' and acts like 'number shown-1'

Also, it doesn't show decimal points ex) if you have 3 herbs, and cast a spell that costs less than 1, it'll still read 3 rather than 2.xx

**Comment by elucent** [comment]
Yeah the herb counts round up. It's just a fundamental inaccuracy, and honestly I'm not opposed to it.

This does cause _one_ issue though, which is that it's difficult to empty pouches and refill them with something else when this is the case. I'll add a means of easily emptying pouches come next update.
