### ISSUE TITLE
Roots 2 plants bug with Aqua Munda by McJty

### ISSUE THREAD

**Issue by AntidermisMC** [RootsTeam/Roots#179]
I can plant stuff on aqua munda's custom farmland (it replaces standard farmland) but as soon as their block gets updated or after a few seconds they uproot. I guess the seeds can be be planted because it's a kind of farmland but then the crop realizes that it is not actual vanilla farmland.  
Was using AM v.0.0.6 and roots 2 0.0009.

**Comment by elucent** [comment]
The crop does nothing different from a vanilla crop block. I can't confirm now, but I suspect this is an issue on McJty's side.

**Comment by elucent** [comment]
Fixed this in the latest update, will be on CurseForge shortly.
