### ISSUE TITLE
Suggestion: ritual that applies spectral to mobs nearby

### ISSUE THREAD

**Issue by gchpaco** [RootsTeam/Roots#186]
Friend of mine suggested this to me, and it seems like a good idea.  Idea would be as long as the ritual is running, it applies the spectral potion effect to mobs nearby the ritual source.

**Comment by elucent** [comment]
When would this actually be useful? You might as well just use something like the Third Eye from Botania or something.

**Comment by elucent** [comment]
I will not likely add this.
