### ISSUE TITLE
[1.10.2] [Bug] Spell size doesn't visually change when running on dedicated server.

### ISSUE THREAD

**Issue by grundyboy34** [RootsTeam/Roots#187]
Spell sizes don't seem to visually change when playing on a dedicated server.
Tested using the Devil's Flower spell.
The appropriate number of rings appeared when tested locally, but the spell that appeared in the world always looks like the size +0 spell, even when the size was greater.

Steps to reproduce:

1. Setup dedicated server with Roots.
2. Craft devil's flower spell with no modifiers, imbue into staff.
3. Craft devil's flower spell with +1 size modifier, imbue into staff.
4. Compare both spells in the world. They will appear identical.

**Comment by elucent** [comment]
Closing as 1.10.2 is no longer supported.
