### ISSUE TITLE
Barrow/Stone circle overlap

### ISSUE THREAD

**Issue by VallenFrostweaver** [RootsTeam/Roots#188]
Not sure if it's intended or not but I noticed some overlap on occasion. See image for reference.
![temp1](https://cloud.githubusercontent.com/assets/13642054/23516007/d194210a-ff63-11e6-9e4c-f7d2e8fe7bcc.png)

**Comment by elucent** [comment]
It happens. I might add some additional checks to try and avoid this happening, but in the end it's not really compromising the usability of either structure so it's low priority.

**Comment by VallenFrostweaver** [comment]
No worries.  I did notice that I found about 5 like this before I clicked this image as an FYI. I did also increase the spawn frequency in the configs as well - just further info.

**Comment by elucent** [comment]
Closing this since it's not a huge issue. Honestly I don't think fixing it is super necessary.
