### ISSUE TITLE
[1.11.2 v0.011] Making Dwindle Dust/Totem Fragments removes enchantments from Hammers

### ISSUE THREAD

**Issue by VallenFrostweaver** [RootsTeam/Roots#189]
As above. If the Hammer is enchanted (ie. Looting/Sharpness, etc.) it will lose all enchants upon being used to make dwindle dust or totem fragments.

Also version 0.011 shows up as 0.010 in all cases but in the mod folder as an FYI.

**Comment by elucent** [comment]
I forgot to update the mod's version for 0.011 in a few files, no big deal.

As for the bug, I'll get it fixed for the next release. Embers should stabilize for a bit soon.

**Comment by elucent** [comment]
Should be fixed now.
