### ISSUE TITLE
Blistering Cold doesn't work -- error, but no crash

### ISSUE THREAD

**Issue by egorananyev** [RootsTeam/Roots#190]
Casting Blistering Cold from a staff has no effect. When right-click and holding, it is clear that the spell is 'charging', but upon release, no particles shoot forward, and the target is undamaged. The following error is printed to the console:
[blistering_cold_error.txt](https://github.com/RootsTeam/Roots/files/819434/blistering_cold_error.txt)

This is run on a private 1.10.2 Forge server, version 12.18.3.2239, using roots-0.208, on a Windows 10 system. Tested with and without modifiers.

Sanctuary spell works as intended, though other spells might be affected as well -- have not tested them.

**Comment by elucent** [comment]
Not maintaining Roots for 1.10.2 anymore. This bug does not render the mod unusable, so I'm going to continue to focus my development efforts towards 1.11.2.

**Comment by LaurenJoanna** [comment]
When used on a projectile staff, this spell crashed the server.
(Ftb beyond)

**Comment by elucent** [comment]
Closing as 1.10.2 is no longer supported.
