### ISSUE TITLE
[Suggestion: Roots 2] Fairy Dust drop change? Fairy change?

### ISSUE THREAD

**Issue by VallenFrostweaver** [RootsTeam/Roots#191]
Perhaps instead of needing to kill a fairy you simply need to right click one with a right hand and it will yield 1 fairy dust per day (kinda like the paper bark tree from Pam's Harvestcraft but an entity)? For some reason killing them for the dust makes me sad. They are so freakin' cute.

Or perhaps the ability to temporarily tame one by feeding it aubergines/pereskia/other-ingredient to make it "friendly" and have it follow behind you (like the OpenBlocks Cartographer did) by carrying a specific "item" on your hot bar or baubles slot (Pan Pipes or whatever) and every now and again it drops a dust but only while following you. If you drop the item or it goes into your pack inventory (or external) the fairy looses interest in you and flies away in a puff of smoke (poof!) and the user will have to "tame" another to have them follow again. 
Furthermore, dust dropping could be turned off by carrying a different lure item so they could be an aesthetic little critter that you can have follow you around (until killed/released).

Just some thoughts. Feel free to close this once you've read it.

**Comment by elucent** [comment]
Fairy dust will have a much better way to be obtained in the near-ish future. Embers has just been sucking away my productivity for the time being. The fairies as they are now are no more than a very small inkling into their future role into the mod.
