### ISSUE TITLE
[1.11.2 v0.011] Wall of the Winds ritual not working

### ISSUE THREAD

**Issue by VallenFrostweaver** [RootsTeam/Roots#193]
I have placed the requisite feather, pereskia bulb and blossom, and the bark of spruce and birch into a pyre and tried lighting it at different times of day, with different quantities (all equal amounts), flat land, hilly, with runestones, without, cleared area, etc. I cannot get it to light. No other prerequisites are listed in the book. What am I missing or is this a bug?

**Comment by elucent** [comment]
Okay, fixed this up, gonna put together a quick bugfix update tonight.
