### ISSUE TITLE
[1.11.2 v0.014] Fairy + leads?

### ISSUE THREAD

**Issue by VallenFrostweaver** [RootsTeam/Roots#196]
Not sure if it's as intended but fairies can be put on a lead though they will not be dragged along by one and instead stay in their area potentially stretching the lead a very long distance (2-4x longer than a vanilla one before breaking). This can be ignored completely but it seemed strange was all.

**Comment by elucent** [comment]
Huh, yeah, that is strange. If they're still breaking, I think I'll just leave it in for hilarity's sake though. :P
