### ISSUE TITLE
[1.11.2 v0.014] Ritual of Sacrifice crash

### ISSUE THREAD

**Issue by VallenFrostweaver** [RootsTeam/Roots#197]
See attached Pastebin for details. Ritual of sacrifice was up and running. I had spawned in a bunch of skeletons surrounded by slabs and covered overhead. They started taking damage (from what I don't know) and the game crashed and can't re-enter without crashing again.

http://pastebin.com/gu8AyNb9

**Comment by Nopotato** [comment]
I also crashed during the Ritual of Sacrifice using a lectern. I had a plate nearby that stayed green for the whole ritual. However, when I shift-right clicked the lectern with book and ink to try and see if it would give me a forbidden book, the game crashed. Here is my crash report: [https://pastebin.com/SURx2ikR]

I can now no longer load the save file, as it will crash the moment I launch it.

**Comment by elucent** [comment]
Fixed both of these issues, will be in the next release.
