### ISSUE TITLE
[1.11.2 v0.014] Ritual of Life does not bestow "regenerate the vitality of nearby creatures"

### ISSUE THREAD

**Issue by VallenFrostweaver** [RootsTeam/Roots#198]
As stated in the Book of Natural Arts I have found no effect but for crop growth in the area. Does this have another effect that I do not see happening that "regenerates the vitality of nearby creatures"? Is this saturation gain or something?

**Comment by elucent** [comment]
You see the little flashes of green particles around you? That's healing, if you're below max health it will increase your regeneration rate. It won't do this if you're below a particular hunger threshold, so as to not totally break Blood Magic, but it is quite notable.
