### ISSUE TITLE
Lighting / shader issues around moonlight ritual - Minecraft 1.11.2, Roots 2 0.014

### ISSUE THREAD

**Issue by knord1** [RootsTeam/Roots#199]
There seems to be some kind of incorrect lighting around the moonlight stones.

I see it on the Psi programmer and with Light Level overlay active.

I tested this with only Forge, Roots and LLOvelay installed.

When I have LLOverlay active and get within ~45 blocks all light info fill the entire block instead of showing the number.

![2017-03-18_15 06 34](https://cloud.githubusercontent.com/assets/8095995/24072802/ea2542f4-0bec-11e7-8ebb-ae020f9ed866.png)
![2017-03-18_15 06 39](https://cloud.githubusercontent.com/assets/8095995/24072803/ea280b6a-0bec-11e7-80b3-849f60811556.png)

**Comment by elucent** [comment]
This is a known bug, I'll try and figure out what's causing this.

**Comment by elucent** [comment]
I think this is fixed now. I'll close, then when I get the next release out, let me know if it's still happening!
