### ISSUE TITLE
[1.11.2] Too Many Fairies!

### ISSUE THREAD

**Issue by ThomasAunvik** [RootsTeam/Roots#200]
Well, i was AFK a while doing some server stuff. I had a fairy pack just beside where my base was, so it was always chunkloaded, after some time i got HUGE lag when i got outside of my house. And what i saw infront of me was a massive chunk of fairies flying around. Had to do `/killall @e` just to get rid of them, beacuse i did not know what the entity name was. So i died, and when i killed the fairies they dropped tons of fairy dust! Many stacks of it. Here is an image how horrible it was:

![Fairies Everywhere](http://i.imgur.com/CXsRanc.jpg)

**Comment by elucent** [comment]
Oh dear! I have a safety check to prevent this, I wonder why it didn't work?

**Comment by ThomasAunvik** [comment]
Also, this might be a very huge problem where the global spawnpoint/spawn is. Beacuse it seems that the server spawn is chunkloaded too. My base was next to spawn, and i think the spawn of the world was even closer to the fairy pool.

**Comment by Fuzzbling** [comment]
I can second this. It wasn't near the world spawn, but the pool was near a player's base and chunkloaded.

![Image of Fairies](http://i.imgur.com/MhVPWtc.png)

**Comment by elucent** [comment]
Okay, I *think* I may have the root of the problem figured out. I'll try and push a bugfix release soon, let me know if there's issues still.

**Comment by Fuzzbling** [comment]
I think the latest version fixed this, I've not had another occurrence. Thank you @elucent !

**Comment by elucent** [comment]
Good to know!

**Comment by MixSt** [comment]
v. 2-0.016. New world. 
![2017-04-27_20 37 04](https://cloud.githubusercontent.com/assets/16831417/25495279/ae690f8c-2b8d-11e7-8955-d569d48f15a3.png)
