### ISSUE TITLE
[1.11.2 v0.014] Roots2 Screen Darkening

### ISSUE THREAD

**Issue by WhiskersRS** [RootsTeam/Roots#201]
The books look to be darker than intended. Possibly the same screen darkening issue that was happening with the embers codex before Embers v0.205.

Minecraft 1.11.2
Forge1.11.2-13.20.0.2229

![2017-03-19_13 29 47](https://cloud.githubusercontent.com/assets/25867491/24083845/f108a5d2-0cac-11e7-90e3-6cea18557d6d.png)

![2017-03-19_13 30 26](https://cloud.githubusercontent.com/assets/25867491/24083843/e04efd9a-0cac-11e7-8537-c74213f09615.png)

**Comment by elucent** [comment]
Yes, most likely. I'll fix it soon.

**Comment by elucent** [comment]
Fixed, will be in a release shortly, sorry for the long wait!
