### ISSUE TITLE
[1.11.2 v0.014] Enchanted items texture

### ISSUE THREAD

**Issue by vail0n** [RootsTeam/Roots#203]
Enchanted items texture glitchout in 4 chanks radius around stone circles.

Minecraft 1.11.2
Roots 2-0.0.14
Forge 13.20.0.2259

![2017-03-20_22 47 13](https://cloud.githubusercontent.com/assets/26553642/24116984/82cabf48-0db9-11e7-9a44-c61b3d2dcd31.png)
![2017-03-20_22 47 21](https://cloud.githubusercontent.com/assets/26553642/24116991/873eb480-0db9-11e7-988f-fd62e2430ce4.png)

**Comment by elucent** [comment]
Yeah I have something weird going on with those. I'll figure it out soon, but I need to wrap up a particular Embers feature first.

**Comment by elucent** [comment]
Fixed, will be out in the next release.
