### ISSUE TITLE
Spirit Herb Crafting does not work

### ISSUE THREAD

**Issue by darkshadow543** [RootsTeam/Roots#204]
Same version as the last bug report I made, Have everything correct, does not work.
![2017-03-20_17 59 18](https://cloud.githubusercontent.com/assets/14943673/24123760/35c9e466-0d97-11e7-8b2e-fd9460cb418c.png) Heres a picture.

**Comment by darkshadow543** [comment]
Version 2-0.014

**Comment by VallenFrostweaver** [comment]
Moonglow doesn't either. Version v0.014

**Comment by Roxforbraynz** [comment]
@VallenFrostweaver [Moonglow requires a red tulip, not a white one.](https://github.com/RootsTeam/Roots/issues/202)

**Comment by elucent** [comment]
This recipe's metadata _should_ be correct, but I could be wrong. The Moonglow's was messed up for a separate reason that this recipe does not share.

**Comment by elucent** [comment]
Found the issue and fixed it, will be in the next update, whenever I have time.

**Comment by darkshadow543** [comment]
For now, I just spawned in it due to the bug, Its something I do in the last resort

**Comment by Ramanati** [comment]
None of the recipes are able to work anymore in the newest update of my saved game. Placed them exactly as I did previously to get the flowers, but this time nothing happened, even rotating them to different compass points.

**Comment by elucent** [comment]
Okay, closing this since I'll get a new version out soon!
