### ISSUE TITLE
[1.11.2] Roots 2 moon circles entity messing with an unknown render function.

### ISSUE THREAD

**Issue by Rosethorns** [RootsTeam/Roots#206]
It appears as though the roots 2 moon circle entity is messing with render function used by a couple of mods. This was found while using both the chisels and bits tape measure and the Light Level Overlay Reloaded f4.

While within render distance of the moon circle entity colour is removed from chisels and bits tape measure lines, boxes and text. And while using the Light Level Overlay the normal colored numbers become glitchy coloured splotches.

The moment you move out of render distance of the moon circle entity the issue stops.

Recreate:
1. have a mod like Light Level Overlay Reloaded installed.
2. turn LLOR on
3. Approach Roots 2 Moon Circle

Versions:
Minecraft: 1.11.2
Forge: 13.20.0.2260
Roots 2: 0.014

**Comment by elucent** [comment]
I've seen this and I do not know what is going on. When I get back to Roots 2 I'll fix it up, but I have to wrap up the next Embers update first.

**Comment by elucent** [comment]
_Should_ be fixed in my dev environment, I'll get a new release out soon hopefully!
