### ISSUE TITLE
Unresponsive Moon Circles

### ISSUE THREAD

**Issue by Ramanati** [RootsTeam/Roots#207]
Updated to latest Roots 2. Previous saved game and new game both have the midnight ritual not working. Tried all moon circles in the surrounding biomes and set the 5 plants in rotated fashion, in case they had to be set in a specific compass point, and not a single flower changed.

**Comment by elucent** [comment]
What are you trying to create?

**Comment by Ramanati** [comment]
I was first having an issue with the moonleaf, but after posting this, I say the solution with the red tulip. Now the only issue is the Spirit Herb recipe is not working and I just have no clue on how to make ruinstones.

**Comment by Ramanati** [comment]
![2017-03-26_23 40 55](https://cloud.githubusercontent.com/assets/26669108/24341208/c643b6f8-127d-11e7-8a0d-418b49e6ce79.png)

Netherwart in the center is fully grown at age 3.

**Comment by Ramanati** [comment]
read other issues and solutions. All bugs are already accounted for. Just waiting for the next update. (Was having issues with moonleaf and spirit leaf as well, but saw the other posts) But how do you make ruinstones? I'm stumped on that one
