### ISSUE TITLE
[2.0.014] Ritual Sylvan glow doesn't work

### ISSUE THREAD

**Issue by Nopotato** [RootsTeam/Roots#208]
version 2.0.014.

I can't use kindling to start the pyre. I am not sure exactly how to do it, and the ingame book is too vague to know if I am doing it right. 
I have tried lighting it with the correct ingredients (in the correct order?) in the day, night, next to a stone circle, next to fairies, but no spirit comes to write in the book.
![screenshot 2017-03-26 17 40 41](https://cloud.githubusercontent.com/assets/3679297/24333202/faab8cc4-1253-11e7-8996-fd551dd98436.png)

**Comment by elucent** [comment]
What dark bark are you using? Dark Oak or Spruce? It should be the former if it's not.

Also make sure there's no other Numena nearby. The ritual will fail if one is already present.

Finally, the lectern is not filled using the ritual. The ritual will summon the spirit, but to actually use the lectern requires a different process. To quote the book:

> With a nature spirit inhabiting the area, simply place any book, then ink on the lectern. Crouch down and activate the lectern with a hand, and the spirit will write down its knowledge into the book.

I think that should explain what to do after you summon in a Numen.

**Comment by elucent** [comment]
Whoops, reopening in case this ends up actually being a real bug.

**Comment by Nopotato** [comment]
I was using the wrong bark, I got it working thanks for the help.
