### ISSUE TITLE
How does one make Runestone

### ISSUE THREAD

**Issue by Nopotato** [RootsTeam/Roots#209]
In the in game book, it says its forged from regular stone under moonlight, but I can't figure how. I tried placing cobblestone and regular stone in the moonbeams, and i tried just crafting it with a crafting bench at midnight. But I can't figure out how to make it.

**Comment by Ravin890** [comment]
Throw a piece of stone under the center moonbeam

**Comment by Nopotato** [comment]
I have put stone in the central moonbeam but I can't seem to get it to change.
I can't open your link even with copy paste and removing the _ .
![screenshot 2017-03-27 10 52 47](https://cloud.githubusercontent.com/assets/3679297/24348422/f537414c-12db-11e7-856a-743868232d85.png)

**Comment by Ravin890** [comment]
...throw not place...
[Here is link again, found out how to use the url thing properly](https://www.youtube.com/playlist?list=PLQzDSnrhrcyzJgM7KEhuZT221wvhkbnI_)
