### ISSUE TITLE
(1.10.2) crash with Roots 2 while creating a world

### ISSUE THREAD

**Issue by Hypsellis** [RootsTeam/Roots#211]
I get this crash with Roots 2 on 1.1.2 after a long time of loading when creating a world. https://pastebin.com/ag718HDR

**Comment by elucent** [comment]
sorry mate, java's too OP so i had to nerf it.

**Comment by Hypsellis** [comment]
What do you mean ?

**Comment by Hypsellis** [comment]
If it can help, the problem occurs only when trying to create a world. The world creation stuck at 6% and the game seems to reload again and again without being able to get out, like if it was stuck in an eternal loop, the log repeats it. It seems to indicate that something goes wrong with Roots structure generation, which prevent the world to generate correctly. And after aproximately 30 minutes of waiting, the crash occurs.

**Comment by Sunconure11** [comment]
The crash is blaming Harvestcraft.

**Comment by Hypsellis** [comment]
Not only HarvestCraft, a lot of mod appears in this crash if you look well.

**Comment by Hypsellis** [comment]
I finally found the cause of the crash. Like I thought this bug isn't simple at all, it involves not only two mods but a particular combinaison of mods. Thanks to the crashreport I found all the mods involved in the bug. I made all the necessary tests for being sure that all these mods are involved and required for the bug happens.
- Roots 2
- FuturePack
- Mekanism
- Natura
- Pam's HarvestCraft
- Quark
- Taiga
The dependancies like Tinker's Construct and Mantle could be involved too. Anyway here is the crash report https://pastebin.com/0wuHQ9n1 and the log (sorry I haven't been able to post it on Pastebin, the logs is too long. Like I told before, the logs repeats it without end until it crashes, like if it was blocked in an eternal loop, unable to load chunks) [latest.txt](https://github.com/RootsTeam/Roots/files/888905/latest.txt)

**Comment by Sunconure11** [comment]
https://www.reddit.com/r/feedthebeast/comments/63433a/quick_update_on_my_mods/

: |

**Comment by Hypsellis** [comment]
Seriously ? A joke ? There was many other ways to make a better joke. While to just close this issue, Elucent could have told me it was 1st april joke, and this crash was desired as it seems. This joke made me lost to me and some of my friends a lost of time. And now I involved many modders for nothing. In final everybody lost his time for a stupid and shitty joke.
