### ISSUE TITLE
Despite the nature of your 1.10.2 port for Roots 2, there are some issues you should fix

### ISSUE THREAD

**Issue by Sunconure11** [RootsTeam/Roots#212]
https://www.dropbox.com/s/zacytxouf3i4zy4/Screenshot%202017-04-01%2005.30.39.png?dl=0

Mainly, deal with this screwed up nether star in one of the recipes for your april fools joke.

Totem of Undying backport also does not seem to be functional.

Thatch could use some pruning. https://www.dropbox.com/s/p43x7wzhhl3ug9j/Screenshot%202017-04-01%2008.51.21.png?dl=0

Thatch issues also persist on 1.11.2. https://www.dropbox.com/s/b5dkpokwasymu6w/Screenshot%202017-04-01%2020.15.42.png?dl=0

**Comment by ate0ate** [comment]
I'm pretty sure the thatch is supposed to look like thatl. I've never seen it look any other way in mod spotlights or screenshots. I don't think I like this april fools joke at all!I thought there was a serious issue at first, but then I realized there's no way those required ingredients could be anything other than intentional lol.

**Comment by ate0ate** [comment]
Suggestion regarding the April Fools recipes, make them configurable. It was funny to see, but making the mod unplayable is really not that amusing for more than a couple seconds.

**Comment by elucent** [comment]
there is an easy fix to all of these bugs:

update to 1.11.2

**Comment by ate0ate** [comment]
Don't gotta be a dick. Most mods are still being developed for 1.10.2 so your point is moot, mate. Its absolutely fine if you don't want to support 1.10.2 also, but why bother putting out a broken release for it at all then?  Especially if you don't want to hear any issues about it? Bit of a scrub move that is.

**Comment by Sunconure11** [comment]
@ate0ate Stop. Let him develop on what version he wants. Despite it April fools, I thought the port was to some extent, legit, despite elucent's views on 1.10.2, therefore, I opened this issue.

**Comment by elucent** [comment]
@ate0ate what's your in-game username? i may be able to give you some special assistance.

**Comment by Hypsellis** [comment]
Like I told this joke made me lost a lost of time to try to understand the crash I go. And now I involved many modders for nothing. And many people who update Roots lost their progression for nothing. In final everybody lost his time for a stupid and shitty joke. This was the worst joke ever. 1st april doesn't mean to behave as an asshole with people, especially the ones who love his mod and support him.

**Comment by ate0ate** [comment]
Releasing bugged port that is intentionally broken is considered to be malicious software. Anything that intentionally causes crashes like that is considered malware, especially when it is openly admitted. Doesn't matter if your intention is a joke. I'm reporting you to curseforge.

**Comment by ate0ate** [comment]
I suggest others that were victims of this malware also report your experience on its curseforge page.
https://minecraft.curseforge.com/projects/roots 
The report button is on the right.

**Comment by elucent** [comment]
okay, so uh, before you start this...did you think to read the changelog? https://minecraft.curseforge.com/projects/roots/files/2401111

**Comment by elucent** [comment]
like, there was _way more than ample warning_ for this.

in addition to it being april fools day.

this aint on me.

**Comment by Zygus42** [comment]
One person's funny is apparently tons of other people's wasted time.  Reported as unacceptable behaviour.  This IS on you !

**Comment by Sunconure11** [comment]
@elucent LOCK THIS PLEASE

**Comment by elucent** [comment]
i'll lock it if you like, forgot you were getting emails, sorry about that.
