### ISSUE TITLE
[1.10.2] [Bug] JEI recipes are odd

### ISSUE THREAD

**Issue by Zygus42** [RootsTeam/Roots#213]
1.10.2, roots-2-0.015.jar
Many of the recipes for simple items (Mortars, Pestles, Thatch) are showing in JEI as using Eldritch Orichalcum Ingots and Nether stars.  Pretty sure this is not the way it's meant to be.

**Comment by Zygus42** [comment]
Actually, the recipes in the spellbooks are the same, so is not a JEI issue.

**Comment by yrsegal** [comment]
It's an issue with your reading comprehension

**Comment by Tristaric** [comment]
Step 1;
Don't play an FTB pack.

**Comment by elucent** [comment]
sorry mate balance is a harsh mistress. i dont make the rules.
