### ISSUE TITLE
Enchanted items broken/darkened screen with shaders in certain areas

### ISSUE THREAD

**Issue by Aphyxia** [RootsTeam/Roots#214]
Does Roots affect the light in certain areas? In certain parts in the world enchanted items get a box of enchantment effect around them. I tested this also with optifine shaders. Internal shaders made the screen darken when I got into the area. 
Example:
https://gyazo.com/1755b0b6d169b70b5e0be7b248952450

1.11.2
Forge 2252
roots-2-0.014.jar

**Comment by elucent** [comment]
It's a bug with the moonbeams. I've fixed it in my dev environment but I do not know when I will get a new release out.
