### ISSUE TITLE
[1.11.2] [v0.014] [2 Bugs] Moonglow ritual doesn't work and activating a lectern crashes the game

### ISSUE THREAD

**Issue by dmushcow** [RootsTeam/Roots#215]
When trying to summon the moonglow crop on a moonlight circle nothing happens. I tried seven times, checking if I had the correct items, but  still doing nothing. Also my game crashed when I shift+right click the lectern to activate it. I have the following mods installed alongside Roots 2:
AutoRegLib 1.1-4
BabyAnimals 1.11
Giacomo's Foundry 1.3.12
Hopper Ducts 1.4.9
Infernal Mobs 1.11.2
JEI 4.2.10.248
Optifine HD U B7
Quark 1.2-90
TreeChopper 1.1.2
Waystones 3.0.13

**Comment by elucent** [comment]
Fixed in my dev environment, but I apologize: I don't think I'll be able to release the changes soon, Embers is taking priority for the moment and I have a very important project I'm working on in conjunction with it.

**Comment by KyuuGryphon** [comment]
I think my friends and I are getting the same lectern crash here. Roots 2 version 0.016, Forge version 13.20.0.2282. 

Full crash log:
[https://pastebin.com/xsxtTtHF](url)

**Comment by elucent** [comment]
Fixed for next release.
