### ISSUE TITLE
[1.10.2, 2-0.015] Recipes *very* broken

### ISSUE THREAD

**Issue by Boundarybreaker** [RootsTeam/Roots#216]
I'm having some issues with the recipes in Roots right now. I think it might be obvious what the problem is.

![2017-04-23_20 33 49](https://cloud.githubusercontent.com/assets/6722691/25321586/8aedda14-2864-11e7-8a9a-c363bed2a580.png)
![2017-04-23_20 33 45](https://cloud.githubusercontent.com/assets/6722691/25321587/8b0b21c8-2864-11e7-96b5-c9f66145eb7a.png)
![2017-04-23_20 33 33](https://cloud.githubusercontent.com/assets/6722691/25321589/8b0c3b80-2864-11e7-8933-26fe7e8e3301.png)
![2017-04-23_20 33 29](https://cloud.githubusercontent.com/assets/6722691/25321588/8b0b29a2-2864-11e7-9f6f-75120a652600.png)
![2017-04-23_20 33 27](https://cloud.githubusercontent.com/assets/6722691/25321590/8b0c9666-2864-11e7-8b08-248ca20d6593.png)
![2017-04-23_20 33 25](https://cloud.githubusercontent.com/assets/6722691/25321591/8b0ccbcc-2864-11e7-89e3-da325a681fcf.png)

Instead of wood, sticks, stone, and herbs, they need nether stars, eldritch orichalcum, end crystals, and dragon eggs. This definitely doesn't seem right.

**Comment by elucent** [comment]
Yes, you're using the April Fools' Day version. Roots 2 does not exist on 1.10.2 outside of this joke version -- as it says on the file description on CurseForge or in many other places.
