### ISSUE TITLE
Time stop spell prevents caster from moving

### ISSUE THREAD

**Issue by colejagdtiger** [RootsTeam/Roots#217]
When casting the time stop spell the caster is prevented from moving while it is in effect, however you can still attack and recharge the attack cool down, close doors, you may be able to turn however I cannot remember (added that bit because I do not know if you can, or should be able to preform those actions while time is stopped for you).

**Comment by elucent** [comment]
Which version?

**Comment by colejagdtiger** [comment]
Version 2-0.016

**Comment by elucent** [comment]
I've fixed this! Will release a fix soon!
