### ISSUE TITLE
[1.11.2] Too Many Fairies 2! (v. 2-0.016)

### ISSUE THREAD

**Issue by MixSt** [RootsTeam/Roots#218]
Issue looks like as at #200.
I use roots in modpack [All The Mods 2](http://allthepacks.com/atm-2/) on Forge+Sponge server.
![2017-04-27_20 37 04](https://cloud.githubusercontent.com/assets/16831417/25495704/3f0ff036-2b8f-11e7-83da-7f0026bf4633.png)

**Comment by ThomasAunvik** [comment]
It does not look like #200, it is #200

**Comment by LemADEC** [comment]
Any workaround while we wait for a fix?

**Comment by elucent** [comment]
I'll make something to clean up the damage in the next release.
