### ISSUE TITLE
[1.11] Removing items from a lectern/pyre replaces it with what's in your offhand

### ISSUE THREAD

**Issue by quat1024** [RootsTeam/Roots#219]
1. Hold something in each hand, like a shield in the off hand and some bark in the main hand.
2. Right click to place the bark onto a pyre.
3. Right click with an empty hand to remove it.
4. Now your shield somehow found its way onto the pyre!

Also happens with lecterns, and I apologize because I haven't progressed far enough to test it on any other right-clicky items the mod might have \^\^

**Comment by elucent** [comment]
Fixed for next release.
