### ISSUE TITLE
Server disconnect when both Roots & Custom NPC's installed

### ISSUE THREAD

**Issue by DarthJimBob** [RootsTeam/Roots#221]
Hey there, no log output sadly but I've been putting together a modpack that uses both CustomNPC's and Roots 2. I consistently get either the client freeze completely or a server disconnection (as in, even on single player - the embedded server cuts out.) It occurs even with just CustomNPC's & Roots 2 with no other mods installed.

I have no issues with just CustomNPCs or Roots 2 individually. Only the combination of the 2.

I'll let the creator of CustomNPC's know too.

**Comment by Medusalem** [comment]
Here i have a crashlog with the same Problem: https://pastebin.com/204s32rc

**Comment by elucent** [comment]
This is CustomNPCs' fault, the dev has been spoken to.
