### ISSUE TITLE
Fairies not spawning?

### ISSUE THREAD

**Issue by Bienkie** [RootsTeam/Roots#222]
Hi there - really struggling.. Cant seem to get fairies to spawn naturally by their pools? Found three but through day and night waiting nothing spawned..? Am i doing something wrong or is this a bug?

**Comment by VT-14** [comment]
I'm also having this problem on Roots 2-0.017 and Forge 13.20.0.2296.  This is my first time using Roots 2, so I'm similarly not sure if I'm just missing something.

I've visited about 6 different pools (I am even living right next to one).  I have yet to see a single fairy in nearly 48 hours of play.  I've been intentionally visiting the pools at night and have tried waiting from sunset to sunrise.

Recreated in single player with only Roots and Forge.
Manual Debug Crash: https://gist.github.com/VT-14/8e40f0afb9236cf0bd329948b5e65062
FML Log: https://gist.github.com/VT-14/a178fd6049ecf41c38f0e28651127422

**Comment by Bienkie** [comment]
Yeah I'm trying to film a modded series... so wanted to show people the fairies spawning at sunset... waited all night and nothing... did the same at other pools and nothing...

Quite unfortunate :(

**Comment by elucent** [comment]
I uh, might have messed up. Sorry! ;-;

I'll have this fixed in the next version, but you'll need to find new fairy pools. :(
