### ISSUE TITLE
Runic Tablet grey'd out in certain areas of map

### ISSUE THREAD

**Issue by babeast99** [RootsTeam/Roots#225]
In some areas, my runic tablet is fully lit up. Other places, its grey'd out and seems like i am doing something wrong. 
![2017-06-08_13 33 20](https://user-images.githubusercontent.com/29288702/26949535-31c52348-4c4f-11e7-9107-22a4b440b207.png) Thank you.

**Comment by elucent** [comment]
1.10.2 is no longer being supported.
