### ISSUE TITLE
Shift+right clicking on lectern does nothing

### ISSUE THREAD

**Issue by Caopr** [RootsTeam/Roots#228]
I I succesfully did the Sylvan glow ritual Divination plates even glowing But placing a book and an ink sac on the Lectern then Shift Right clicking with an empty hand nothing happens. Ive tried the ritual in 2 different areas with the same problem

![2017-06-17_07 56 27](https://user-images.githubusercontent.com/29389055/27252703-d2f61030-5332-11e7-8e5d-520d71e4a18d.png)

I disabled all other mods  and tried again in creative and the same problem occured with a crash saying 

The game crashed whilst ticking block entity
The game crashed whilst ticking block entity
Error: java.util.ConcurrentModificationException

[Although I did spam it a bit after it wouldent work on the test]

I am using Roots-2-0.020.jar

Great mod btw

**Comment by elucent** [comment]
Use a Birchbark Tome. This might be undocumented in current builds, but the entire system is being removed in the next update so it's kind of moot.
