### ISSUE TITLE
Iam new to spellcraft.

### ISSUE THREAD

**Issue by Zekkan74** [RootsTeam/Roots#231]
I am using the version 1.11.2 of the mod but since i am new i have no idea of what to do in order to progress in it. I already got the book made  a pyre and a imbuer, but i have no idea of how to use them.
If someone would tell me how to use them or proceed in the mod it would help a lot.
(by the way, i have not found tutorials of this version of the mod)

**Comment by elucent** [comment]
There are books that explain how things work, and Mischief of Mice has good videos showing how to use the mod.
