### ISSUE TITLE
Question: structures in config file

### ISSUE THREAD

**Issue by rosareven** [RootsTeam/Roots#236]
I want to make the starting hut spawn more frequently but I'm a bit confused by what's what in the config file, under structure. 

1. What's a barrow? 

2. The description for "hutChance" variable is a copy of the moonlight circle's, so it seems "hutChance" is missing its description. I assume this is the right variable for the starting hut?
```
    # Configures the generation chance of the Moonlight Circle structure. Higher numbers mean less structures. [range: 0 ~ 32767, default: 180]
    I:hutChance=100
```

**Comment by elucent** [comment]
Yes, sorry for the typo in the config.

Barrows are a slightly rarer structure. They're ancient graves dug into the ground with loot chests and an invisible spawner inside that spawns zombies and skeletons. You can't remove the cursed spawner from the site...yet.

**Comment by rosareven** [comment]
Thanks Elucent! By the way I look forward to the 1.12 update.
