### ISSUE TITLE
Moon Circle Lights Not Appearing (MC 1.12, Roots 0.025)

### ISSUE THREAD

**Issue by siskow** [RootsTeam/Roots#237]
The light beams for the moon circle are not showing up for me.  I have tried disabling all mods except roots and the issue still persists.  I have also experimented with different graphics settings and it has had no effect.  Just wanted to inform you of the issue.  I am playing on OSX by the way.

**Comment by SudzBud** [comment]
Why did you close this, I have the same issue?

**Comment by elucent** [comment]
This is not an issue. It is a change in the functionality of the circles. Read the book of herblore to find the updated behavior.
