### ISSUE TITLE
2.0.025 (1.11.2) No moon beam at moonlight circles during full moon

### ISSUE THREAD

**Issue by rosareven** [RootsTeam/Roots#238]
I haven't seen any moonlight circle working during full moon. There's no central beam and there's no herb creation (although it could be me placing them wrong - the markings are really hard to see). Runestone creation works fine though.

Edit: I just tried in creative and herb creation does work, my bad. The moon beam still doesn't come up though until I plant everything.

More edit: In fact it seems like I can create moonlight things anytime, I don't have to wait for full moon lol.

**Comment by elucent** [comment]
This is intentional. Read the book or the changelogs before posting an issue.

**Comment by rosareven** [comment]
I'm sorry to bug you but I really struggle to find the changelog that mentions the change to moonlight circle. Can you point me to the right direction please? I would love to know what else I need to know.
