### ISSUE TITLE
Server crash: EntityRitualSacrifice.spawnDrawEffects

### ISSUE THREAD

**Issue by spindisc** [RootsTeam/Roots#239]
The sever crashes when a client player is present efter the Ritual Sacrifice is started.

[Crash-Roots2.txt](https://github.com/RootsTeam/Roots/files/1145838/Crash-Roots2.txt)

**Comment by elucent** [comment]
You are using an extremely outdated version of Roots 2. Always update before posting a bug report. This ritual hasn't even been in the game for a while.
