### ISSUE TITLE
Items not found

### ISSUE THREAD

**Issue by SlobberNockerz** [RootsTeam/Roots#242]
I've used the mod, started trying some rituals and I noticed that there aren't any standing stones that i need for rituals. Is this a problem for me or are they not in the mod?

**Comment by elucent** [comment]
Roots 1 or Roots 2? In Roots 2, standing stones aren't blocks, they're assembled from Runestone and Chiseled Runestone. When a ritual requests a "three-block high standing stone", it means two Runestone blocks in a pillar with a Chiseled Runestone block on top.

**Comment by elucent** [comment]
I'm imagining that this isn't an issue. Reopen if I'm wrong.
