### ISSUE TITLE
Crash when spawn weight = 0

### ISSUE THREAD

**Issue by OrdinatorStouff** [RootsTeam/Roots#243]
A few moments after logging in with:
```
I:sproutSpawnWeight=0
I:deerSpawnWeight=0
```

Game crashes with 
```
Description: Exception ticking world

java.lang.IllegalArgumentException
	at net.minecraft.util.WeightedRandom.func_76273_a(SourceFile:18)
```
[crash-2017-08-06_18.45.41-server.txt](https://github.com/RootsTeam/Roots/files/1203689/crash-2017-08-06_18.45.41-server.txt)

**Comment by elucent** [comment]
Will be fixed in next update.
