### ISSUE TITLE
Guardian of sprites not dropping otherworld essence

### ISSUE THREAD

**Issue by sharpskull2** [RootsTeam/Roots#244]
Roots version 0.208

I have been trying to get otherworld essence from the guardian of sprites boss, and have killed it 6 times so far.
I am only getting 20 otherworld leaves and no otherworld essence from the boss when it is killed.

Other people are having the same problem and only got it to drop after killing it 10 or so times. The tablet says nothing about the otherworld essence being a rare drop and so, could it be a problem with being on a server?

**Comment by sharpskull2** [comment]
I should say that i am playing on a server that runs off of sponge which may be causing the problem

**Comment by elucent** [comment]
Roots 1 is discontinued. Sorry, but it's been 9 months and I was barely planning on revisiting Roots 2. :/
