### ISSUE TITLE
Spells not working 

### ISSUE THREAD

**Issue by HairyDragonBeck** [RootsTeam/Roots#246]
(This is 1.10.2 btw) So for me, the spells I make do not work. I am using [Server.Properties LAN](https://minecraft.curseforge.com/projects/server-properties-for-lan), and for my friend who joins it works fine. No spells are working. Could I get some help on this?

**Comment by HairyDragonBeck** [comment]
Bump

**Comment by Sunconure11** [comment]
1.10.2 is not supported and roots is in a limbo state

**Comment by elucent** [comment]
Not a supported version.
