### ISSUE TITLE
[1.11.2] ClassCastException

### ISSUE THREAD

**Issue by MinecraftPlaye** [RootsTeam/Roots#247]
I've got the following **crash** after joining my local dedicated server. 
It is to be noted that only the Client crashed, the server didn't crash!

https://pastebin.com/4J3AHXqr

This is from the server-log:

> [20:37:30] [Netty Server IO #9/ERROR] [FML/]: NetworkDispatcher exception
> java.io.IOException: Eine vorhandene Verbindung wurde vom Remotehost geschlossen
> 	at sun.nio.ch.SocketDispatcher.read0(Native Method) ~[?:1.8.0_144]
> 	at sun.nio.ch.SocketDispatcher.read(Unknown Source) ~[?:1.8.0_144]
> 	at sun.nio.ch.IOUtil.readIntoNativeBuffer(Unknown Source) ~[?:1.8.0_144]
> 	at sun.nio.ch.IOUtil.read(Unknown Source) ~[?:1.8.0_144]
> 	at sun.nio.ch.SocketChannelImpl.read(Unknown Source) ~[?:1.8.0_144]
> 	at io.netty.buffer.UnpooledUnsafeDirectByteBuf.setBytes(UnpooledUnsafeDirectByteBuf.java:446) ~[UnpooledUnsafeDirectByteBuf.class:?]
> 	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:881) ~[AbstractByteBuf.class:?]
> 	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:225) ~[NioSocketChannel.class:?]
> 	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:119) [AbstractNioByteChannel$NioByteUnsafe.class:?]
> 	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511) [NioEventLoop.class:?]
> 	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468) [NioEventLoop.class:?]
> 	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382) [NioEventLoop.class:?]
> 	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354) [NioEventLoop.class:?]
> 	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116) [SingleThreadEventExecutor$2.class:?]
> 	at java.lang.Thread.run(Unknown Source) [?:1.8.0_144]

Minecraft 1.11.2
Forge Mod Loader version 13.20.1.2454
roots-2-0.025

**Comment by elucent** [comment]
This shit should be getting fixed in like, a short while. Maybe later today. Finally.
