### ISSUE TITLE
Old Root not spawning

### ISSUE THREAD

**Issue by Mulvaaken** [RootsTeam/Roots#249]
I have been unable to get the old root to spawn from breaking tall grass.  I was questioning my patience, but I switched to creative mode and determined that the old root and the ritual tablet are simply not present in the item list... I run a LOT of mods, so I am concerned that one of them may be preventing the items' existence... please let me know what I need to supply you with, thanks!

I am playing 1.11.2 at present, and using roots-2-0.025.jar

**Comment by elucent** [comment]
The mod changed a lot since Roots 1. There are no Old Roots and no resources for the modern mod that I have found are misleading in this regard.

**Comment by Mulvaaken** [comment]
Thanks, elucent... I am *SLOWLY* figuring out how Roots 2 works... there is
a LOT of conflicting info scattered around the web, so I am just teaching
myself the ins-and-outs... appreciate the reply!
