### ISSUE TITLE
Weather Ritual issue

### ISSUE THREAD

**Issue by Oldskoolninja** [RootsTeam/Roots#252]
I noticed this had been answered before sometime last year, but the answer seems to be missing. I'm having the same issue with the downfall rituals not working, everything is set up properly, (I've made the defender armor set) but I'm getting the "No valid ritual found" error when trying to activate.
Minecraft 1.10.2, Roots 0.208

**Comment by Crocodyle1** [comment]
Make sure your Ritual Set-up is at 128 or higher.

See here: https://github.com/RootsTeam/Roots/issues/131

**Comment by Oldskoolninja** [comment]
Got it! Thanks, for some reason the other half of the conversation on that issue wasn't loading for me.
