### ISSUE TITLE
Client Crash from Book of Herblore

### ISSUE THREAD

**Issue by unit285** [RootsTeam/Roots#256]
Using Minecraft 1.12 
Forge 14.21.1.2443

When I open the book of herblore and click inside the ui of the book I get repeatable client crashes.
![crash](https://user-images.githubusercontent.com/32411439/31044509-50c365c0-a596-11e7-9f7d-5f203b6762ff.png)
[crash-2017-09-30_04.05.42-client.txt](https://github.com/RootsTeam/Roots/files/1346301/crash-2017-09-30_04.05.42-client.txt)
[crash-2017-09-30_04.08.49-client.txt](https://github.com/RootsTeam/Roots/files/1346300/crash-2017-09-30_04.08.49-client.txt)
![book of herblore 7414](https://user-images.githubusercontent.com/32411439/31044510-50c52aea-a596-11e7-9ba7-13712cd2ce13.png)

**Comment by elucent** [comment]
Update. Your. Mods. Before. Making. An. Issue.

**Comment by unit285** [comment]
Im very new to mods. Sry. I think i am using the latest version of Roots for 1.12 ?

**Comment by elucent** [comment]
You aren't.
