### ISSUE TITLE
Issue with creating Moonglow leaf on MP server

### ISSUE THREAD

**Issue by craft90** [RootsTeam/Roots#261]
I'm playing All The Mods 3 version 5.1 on a server and today I tried to create Moonglow Leaf. However things didn't work out. While I didn't have any trouble creating the Wild root, the Moonglow leaf just wouldn't work. I tried several combinations and both during day and night. I didn't get further than to having all the stuff light up and send beams to the sky. Then it just sat there and nothing happened. It worked no trouble in a superflat single player world. But not in a BoP Tropical Rainforest with some elevation and half a ring.

Technical details
Forge: 14.23.0.2532
MC 1.12.2
Roots 2-0.103
All The Mods 3 (version 5.1)

**Comment by elucent** [comment]
You probably just have some subtle thing wrong. I've done this on ATM3 with no issues, and if you were able to make wildroot you should be able to make all the others.

**Comment by craft90** [comment]
I had to bring the ground level up so that it was in line with the highest pillar. Then it seemingly worked.
