### ISSUE TITLE
Suggestion: Villagers who sell random staffs beyond what is possible to craft yourself

### ISSUE THREAD

**Issue by Febilian** [RootsTeam/Roots#36]
Like, with more modifier slots used than is allowed typically, for example.

Just a thought I had, feel free to disregard if you wish.

**Comment by elucent** [comment]
I wouldn't necessarily have a problem, just unsure of how I'd make it. But it's a neat idea, even if it does somewhat break my no-worldgen policy. Maybe additional trades for existing villagers?

**Comment by Febilian** [comment]
Perhaps a rare trade for farmer type villagers, or the priests/clerics? Not sure which would fit better haha... maybe the priests/clerics. Farmers maybe could have random petal powders or the growth powder or something? While the priests give you the finished staffs... and a trade to get emeralds could be any kind of petal powder for one emerald? Just so it isn't totally one-way.

Maybe you could add a high-end expensive trade for the mutating powder somewhere too, if that wouldn't break balance too much, since a nether star per one powder is kind of... steep. Oof.

I'm thinking this: if you trade a nether star and a lot of emeralds(anywhere from 16 to 32 or even more, depending) to a certain villager, they'd make you more than one at a time? Like one or two extra at most. So you'd still need the nether star to begin with, but you would have the option to get the powder more efficiently through villager trades - if you can find a villager willing to do that. I would also recommend this to be a high level trade that is not available right away, probably the last tier of trade you can only find by trading with villagers a lot. Make the trade rare as well and I think that might not be a terrible idea balance-wise at least!

**Comment by elucent** [comment]
I found a good way to implement this. I'll be adding some simple staves to priest trades, maybe a few weak ones to farmer trades as well. I think you'll also be able to sell specific staves to priests for 1 emerald.

**Comment by Febilian** [comment]
Another thought on this I had: Maybe you could sell a surplus of old roots and whatnot to farmer villagers for emeralds? I know they have some uses beyond basic spellcraft but sometimes you end up with more than you really need.

**Comment by elucent** [comment]
Oh! That's a great idea! Makes it so people who don't want to play Roots have yet another useful way to get rid of them.

**Comment by elucent** [comment]
An update on this: in theory, this shouldn't be difficult, but none of the modders I have asked have any earthly idea how to do this in 1.8+. I'll keep looking though, since it sounds like a neat feature.

**Comment by elucent** [comment]
^ accidentally closed, whoops.

**Comment by Eyrion** [comment]
@elucent A way around your "no worldgen policy" could be to create something that turns any villager into a Roots Hermit/Druid/Etc. Maybe a poultice, a ritual, burning X incense near them?

**Comment by elucent** [comment]
Perhaps. The main reason this topic is still open is because I have no earthly idea how to add villager trades in 1.10. :P

**Comment by Ravin890** [comment]
I know that immersive engineering adds in a new villager type, so if you do something to change the villager into a new type of villager, then you could ask them how to do it if you don't know.

**Comment by werty1124** [comment]
We have figured out how to do it since this issue was created
