### ISSUE TITLE
Growth spell won't grow

### ISSUE THREAD

**Issue by toddythebody** [RootsTeam/Roots#70]
I can get the spell to work, but when I log off and then back on to a server and do the ritual on myself, there is no growth effect when I right click with an empty hand. I have to kill the player, and then I can get the growth spell to work as it should. I can continue to redo the growth spell until I log out and back in again. Then I have to kill the player once again. I'm playing the Avant 3 modpack.

**Comment by elucent** [comment]
Is this on the latest version?

**Comment by toddythebody** [comment]
1.10.2-0.109.0

**Comment by werty1124** [comment]
Cant seem to be able to reproduce this

**Comment by toddythebody** [comment]
It's every time for me.  I can do the growth ritual and get the green leaf indicators, but right click does nothing on plants until I kill the player and do the spell again.  It could be the pack or multiplayer.  I'm playing on a server with the Avant 3 modpack and most updated version.  We are a group of youtubers. If it's helpful, I could make an unlisted video showing you want happens for me and give the link.

**Comment by werty1124** [comment]
Did you start roots on a version before 0.108.0 and update to 0.190.0?

**Comment by toddythebody** [comment]
Out pack just came out a little over a week ago. We did upgrade to 109 in our second version. We were probably 108 before. The admin is keeping the pack on the most updated versions of mods.

**Comment by toddythebody** [comment]
I think this issue is related to issue #94

**Comment by elucent** [comment]
These are being removed in the next update regardless, so this is one issue we won't be fixing.
