### ISSUE TITLE
Cannot see the diagram in the book

### ISSUE THREAD

**Issue by oks1998** [RootsTeam/Roots#84]
In the runic tablet, there is diagram to see ritual structure, but i cannot see how to arrange the ritual, the diagram just blank, nothing in the diagram, I installed betterfps mod

**Comment by oks1998** [comment]
![image](https://cloud.githubusercontent.com/assets/9070825/17088014/e0c0643c-5247-11e6-84bb-5a772619bb89.png)

**Comment by werty1124** [comment]
That is the arrangement?

**Comment by elucent** [comment]
That appears to be the arrangement. The grid on the tablet page represents the block grid, and the central table represents the altar. Make sure all your standing stones are on the same level as the altar, and that the symbols on the standing stones in the grid match the symbols on the ones that you place down.

Also, what Roots version is this? The animalsummoning title localization should have been fixed a long time ago.

**Comment by oks1998** [comment]
sorry, My mistake, it just show as normal, I dont know why after I reopen the minecraft, it show up the arrangement again, anyway it work like normal. thanks :) 

BTW: this is a interesting mod
