### ISSUE TITLE
Flare Orchid cannot be created - again?

### ISSUE THREAD

**Issue by VallenFrostweaver** [RootsTeam/Roots#87]
v1.10
Following the instructions on the tablet, plant a blue orchid in the nether (i tested on dirt and grass), then surround it with netherrack (tried both at the level of dirt and at the level of the flower - also tested with lit and unlit with fire), under fire resistance effect (used a 3min drinking potion), toss a blaze rod and bucket of lava (not placed but tossed both) near (and tried on top too) the flower, then use the mutating powder on the flower. No results. When testing with the netherrack on fire the items were constantly burned up though I saw on issue #7 that you were changing the recipe and the instructions on the tablet did not state anything about needing anything on fire (though I tested with and without just in case).

Did I miss something here or is this not working as intended?

EDIT: I'm not having any luck making the Radiant Daisy either. Hm.
2nd EDIT: No luck with the Midnight Bloom either.

I tried in old worlds and in new ones. I can't seem to create these 3 Spell component flowers via the rituals.

**Comment by elucent** [comment]
That just sounds like a general error with the mutation system. I'll look into it (either that, or they're going to be removed in the next update anyway).

**Comment by VallenFrostweaver** [comment]
What? Removing? Ack! What can I cover in your mod that isn't going to be removed besides the basics and staves then if you don't mind sharing?

**Comment by elucent** [comment]
Well, the really powerful spells have been slated to be removed (actually moved to a later point in progression in the future, but we're quite a ways from getting there) for a while now, they only existed to give a mod that lacked endgame a little bit of endgame. By the time they get formally removed (in an update coming in a few weeks probably), there will be mobs, boss battles, four new spells, and three new casting methods to show off, as well as some decorative blocks.

**Comment by VallenFrostweaver** [comment]
Ok then. Wow. You guys are busy. I'll focus on the altar set up and the different stones then and hold off until the next big update after that. Thanks!

**Comment by elucent** [comment]
The flowers have been removed, though the components themselves remain so that previous staves with the spells on them don't cause crashes.
