### ISSUE TITLE
Downfall Control Weather Magic not working

### ISSUE THREAD

**Issue by VallenFrostweaver** [RootsTeam/Roots#93]
Tried this ritual (yes, with the mundane standing stones per the grid) and it states "no valid ritual found" for both turning the rain on and off. Tried replacing items, blocks, etc. and still no success. Also tried in multiple biomes. Version .110

**Comment by werty1124** [comment]
Try above Y 128

**Comment by VallenFrostweaver** [comment]
This is still not functioning at higher altitudes. I'm in .112 version now and at Y132. The particles activate (like a spraying effect), I get a message saying "no valid ritual found" and the lily pad is stuck on the altar with no rain. I cannot remove the lily pad and I have to break the altar to stop the rotating animation of the lily pad.

**Comment by elucent** [comment]
That's strange. Let me see if I can replicate this. Anything showing up in the logs?

**Comment by elucent** [comment]
I have not been able to replicate any issues relating to the rain creation ritual, but there was an issue I didn't know about relating to the banish rain ritual. I'll fix it now.

**Comment by elucent** [comment]
Never mind, there was an unnecessary weather line in the banish rain ritual. I'm still not totally sure exactly what your problem was, but this might have fixed it.

**Comment by SpartanSamuel** [comment]
I'd like to reopen the ticket, actually. Below Y=128, the ritual is "invalid". Unless there's something referring to that in the tablet specifying this, then it should classified as a bug. There's no way I would have figured this out on my own without looking at other issues on here.

**Comment by elucent** [comment]
Roots is gonna be getting a full-on rewrite anyway, I might get around to fixing up these issues at some point, but I'm more focused on the redesign of the mod at the moment.
