### ISSUE TITLE
Roots Command not showing in /help

### ISSUE THREAD

**Issue by Starza4TW** [RootsTeam/Roots#95]
Trying to call /help on a server running roots will result in an unexpected error on the page that contains the roots command. 
Log: http://pastebin.com/4yDqtybP

/help also fails sometimes in singleplayer when using roots, not sure if related or not.
Log: http://pastebin.com/viSHx6hx

Installed:
MC 1.10.2
Forge 12.18.1.2046
Roots 0.110

**Comment by Redlotus99** [comment]
https://github.com/matthewprenger/HelpFixer/issues/9

**Comment by StevenB83** [comment]
Having the exact same issue myself.  We get the exact same errors on the server when a user tries to use the /help command.

Steven.

**Comment by Starza4TW** [comment]
What I was thinking, net.minecraft.client.resources.I18n can only be used client side.

**Comment by StevenB83** [comment]
Indeed, this seems to be the line of code it stops on: [RootsCommand.java#L31](https://github.com/RootsTeam/Roots/blob/master/src/main/java/elucent/roots/command/RootsCommand.java#L31)

I don't know enough to fix it, but shouldn't be too difficult.

Steven.

**Comment by Redlotus99** [comment]
I see most mods doing something like

` @Override
    public String getCommandUsage(ICommandSender sender) {
        return getCommandName() + " <subcommand> <args> (try '" + getCommandName() + " help' for more info)";
    }`

**Comment by Redlotus99** [comment]
Any word on this possibly being fixed?

**Comment by Starza4TW** [comment]
Last I checked the whole team is working on [The Modding Trials] (https://www.reddit.com/r/feedthebeast/comments/4tnq0k/the_modding_trials_official_announcement_and/), so I doubt we will see anything done with the issue until next week.

**Comment by elucent** [comment]
I have some time over the weekend where I plan to go through the current issues and fix them all. I will need to take some time to disable most of the other things we've been working on, though, since many of them are somewhat incomplete.

**Comment by Redlotus99** [comment]
Sounds good thank you.

**Comment by elucent** [comment]
Fixed, just need to fix the other stuff the latest Forge update broke before I get some kind of release out.

**Comment by Redlotus99** [comment]
Appreciate it
