### ISSUE TITLE
Bug: Shatter Staff won't break blocks

### ISSUE THREAD

**Issue by squirrelkiller** [RootsTeam/Roots#99]
The staff simply is not doing what it says it should, tested on wood, stone, iron ore, and dirt.

**Comment by squirrelkiller** [comment]
An update, after messing with it some more I got it to break a block, about 4 blocks away in a direction I was not looking. I am going to guess there is an issue with ray casting and detecting where one is looking and if there is a block where you are aiming.

**Comment by elucent** [comment]
What Forge version are you using? I've heard the mod is being affected by some changes in Forge 2046 and up (approximately, haven't tested myself).

**Comment by elucent** [comment]
Fixed, there was a weird bug in the spell. Honestly not sure what changed it from previous versions, but it's fixed now!
